Add BadPacketsV
GrimAnticheat/Grim pull request #1297
Opened 2024-01-11 18:11 UTC by z7087

Check for invalid finished digging packets
Should patch #1293 ~~#1296~~ but I only tested it on Spigot 1.8.8

2024-01-12 02:31 UTC, ManInMyVan commented
Could also fix #1133

2024-01-12 05:39 UTC, z7087 commented
I think it is not enough as a fix for that

2024-01-12 06:53 UTC, ManInMyVan commented
> I think it is not enough as a fix for that

Should atleast flag it tho

2024-01-12 10:48 UTC, z7087 commented
> > I think it is not enough as a fix for that
> 
> Should atleast flag it tho

Players can bypass it by send a start_digging packet before send the finished_digging packet that used for velocity

2024-01-12 18:43 UTC, SamB440 commented
Falses when breaking blocks in a protected region in my testing (Paper 1.20.4, 1.20.4 client)

2024-01-13 05:40 UTC, FyxarDev commented
> > > I think it is not enough as a fix for that
> > 
> > 
> > Should atleast flag it tho
> 
> Players can bypass it by send a start_digging packet before send the finished_digging packet that used for velocity

that going to flag fastbreak

2024-01-13 06:27 UTC, ManInMyVan commented
> that going to flag fastbreak

99% of the time it mines air (check for breaking air?), I haven't tested it yet, but it may not flag when insta mining air.

2024-01-13 06:53 UTC, z7087 commented
> Falses when breaking blocks in a protected region in my testing (Paper 1.20.4, 1.20.4 client)

so #1296 can be vanilla :(
hope the Fastbreak check will get improved

2024-01-13 18:00 UTC, FyxarDev commented
> > Falses when breaking blocks in a protected region in my testing (Paper 1.20.4, 1.20.4 client)
> 
> so #1296 can be vanilla :( hope the Fastbreak check will get improved

if it that easy they already patch the velocity this way and not the workaround

2024-01-14 10:31 UTC, 0-x-2-2 requested changes

2024-01-14 10:31 UTC, 0-x-2-2 commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsV.java
> +                        // Ends the client prediction introduced in 1.19+
This is wrong and it is also wrong inside of Grim where you took this code from.

2024-01-14 10:31 UTC, 0-x-2-2 commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsV.java
> +                        } else { // The client isn't smart enough to revert changes
The client is never smart enough to revert the changes like that even on 1.19+ if you don't sync blocks.

2024-01-14 10:31 UTC, 0-x-2-2 commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsV.java
> +                            ResyncWorldUtil.resyncPosition(player, digging.getBlockPosition());
I wonder if this check should be moved to where Grim is already processing this data. There are possible exploits here with how little sanitization of these packets is done.

2024-01-14 10:34 UTC, 0-x-2-2 commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsV.java
> +                        // Ends the client prediction introduced in 1.19+
![Screenshot](https://github.com/GrimAnticheat/Grim/assets/9968651/5b42ac63-d314-4346-a121-b0a712640442)

This is closer to the correct solution.

```java
ResyncWorldUtil.resyncPosition(player, facePos);
FoliaCompatUtil.runTaskForEntity(player.bukkitPlayer, GrimAPI.INSTANCE.getPlugin(), () -> {
    // Ends the client prediction introduced in 1.19+
    if (player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_19) && PacketEvents.getAPI().getServerManager().getVersion().isNewerThanOrEquals(ServerVersion.V_1_19)) {
        player.user.sendPacket(new WrapperPlayServerAcknowledgeBlockChanges(packet.getSequence()));
    }
}, null, 0);
```

2024-01-14 10:36 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsV.java
> +                        // Ends the client prediction introduced in 1.19+
Is this what causes a block state desync that I'm seeing with Grim? (stand still, right click trapdoor in protected region that doesn't allow use, right click again, open state is desynced)

2024-01-14 10:43 UTC, 0-x-2-2 commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsV.java
> +                        // Ends the client prediction introduced in 1.19+
Most likely!

2024-01-24 10:46 UTC, closed without merging