Add an entiy blacklist for reach check
GrimAnticheat/Grim pull request #1388
Opened 2024-03-11 22:19 UTC by Souipi

Implementation of #1386. 

Btw there is a better way to do that at line 89 ? (Entity = "minecraft:" + Entity;)

2024-03-12 13:07 UTC, SamB440 requested changes

2024-03-12 13:07 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +                for (String Entity : ignoredEntitiesList) {
Entity -> entity

2024-03-12 13:07 UTC, SamB440 commented on src/main/resources/config/en.yml
> +  # What entities should we ignore when a player is fighting them ?
```suggestion
  # Which entity types should be ignored by the reach check?
```

2024-03-12 13:07 UTC, SamB440 commented on src/main/resources/config/en.yml
> +  ignored-entities:
I would add the display/interaction entity types as a default as those are currently unsupported by Grim

2024-03-12 13:07 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +            List<String> ignoredEntitiesList = GrimAPI.INSTANCE.getConfigManager().getConfig().getListElse("Reach.ignored-entities", null);
This should be cached and made into a Set, the default can be a List.of() instead of null, avoiding the null check. You also need to handle the reload method.

2024-03-12 14:19 UTC, Souipi commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +                for (String Entity : ignoredEntitiesList) {
I can't due to conflict, do you have a batter variable name idea ?

2024-03-12 14:19 UTC, Souipi commented on src/main/resources/config/en.yml
> +  # What entities should we ignore when a player is fighting them ?
Ty ^^

2024-03-12 14:26 UTC, Souipi commented on src/main/resources/config/en.yml
> +  ignored-entities:
Wdym ?

2024-03-12 14:30 UTC, Souipi commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +            List<String> ignoredEntitiesList = GrimAPI.INSTANCE.getConfigManager().getConfig().getListElse("Reach.ignored-entities", null);
I don't really understant what you mean about the .startsWith...

2024-03-12 16:10 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +            List<String> ignoredEntitiesList = GrimAPI.INSTANCE.getConfigManager().getConfig().getListElse("Reach.ignored-entities", null);
When creating the cache, prefix any that are not prefixed by `minecraft:`.

2024-03-12 16:10 UTC, SamB440 commented on src/main/resources/config/en.yml
> +  ignored-entities:
https://minecraft.fandom.com/wiki/Interaction

These allow for custom hitboxes but are unsupported by Grim currently

2024-03-12 17:16 UTC, SamB440 commented
Also edit your PR description to include the `closes #<issue>` keyword so that the issue will automatically close when this pr is merged

2024-03-12 17:22 UTC, Souipi commented
> Also edit your PR description to include the `closes #<issue>` keyword so that the issue will automatically close when this pr is merged

Oh yea i'll do that

2024-03-12 17:26 UTC, Souipi commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +            List<String> ignoredEntitiesList = GrimAPI.INSTANCE.getConfigManager().getConfig().getListElse("Reach.ignored-entities", null);
Like i only prefix evertything who not prefixed by `minecraft:` and the rest i ignore it ? 
So i need to hard cod the`minecraft:` on the code by myself ?

2024-03-12 17:30 UTC, Souipi commented on src/main/resources/config/en.yml
> +  ignored-entities:
Oh yea that could be great, but if it's unsupported by Grim i don't have the knowledge and the time to do that...

2024-03-12 18:08 UTC, AoElite commented
If the block model engine is using https://minecraft.fandom.com/wiki/Interaction then we should just add support for this or just exclude it instead of just having a blacklist.

2024-03-12 19:04 UTC, SamB440 commented
Actually Grim already excludes these because they are not a living entity. So I am not sure what flags that issue is referencing. (https://github.com/GrimAnticheat/Grim/issues/1386#issuecomment-1992350000)

2024-03-16 00:21 UTC, Souipi commented
So the PR is useful or not ?

2024-04-16 00:15 UTC, Symmettry commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +                for (String Entity : ignoredEntitiesList) {
"otherEntity"?

2024-04-17 09:57 UTC, Pablete1234 commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +    private List<String> ignoredEntitiesList;
Given the only use of this collection is a contains check, consider using a Set instead of a List

2024-04-22 03:59 UTC, AoElite commented
I think the actual issue this was trying to resolve should be fixed instead. We don't know what the actual issue is with that plugin it seems.

2024-04-22 19:50 UTC, Souipi commented
> I think the actual issue this was trying to resolve should be fixed instead. We don't know what the actual issue is with that plugin it seems.

That not wrong

2024-08-03 14:52 UTC, closed without merging