Support for some 1.20.5 attributes
GrimAnticheat/Grim pull request #1439
Opened 2024-04-24 09:53 UTC by SamB440

Working on 1.20.5 update. I'll also update block collisions once packetevents merges the 1.20.5 PR (generally waiting on packetevents to test stuff).

Need to get shulkr working as well so I can view .4 -> .5 diff

2024-05-03 16:15 UTC, SamB440 commented
Gravity wrongly affects vehicle and stepup seems to be broken

2024-05-04 01:12 UTC, Symmettry requested changes
Looks pretty good, but i think there are some issues with your interact range changes

2024-05-04 01:12 UTC, Symmettry commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
You're using getBlockInteractRangeAttribute() for both 4.5 and 6. I think you did something wrong?

2024-05-04 01:12 UTC, Symmettry commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +        Vector endVec = trace.getPointAtDistance(distance);
Now you're using it for 4.5, 5, and 6?

2024-05-04 08:30 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
The numbers that were there before don't make sense and seem like magic numbers

2024-05-04 10:21 UTC, Symmettry commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
If you tested it and it works it's fine, but did you test it?

2024-05-04 12:17 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
Yes, I'll test some more & see if aoelite or someone knows why these numbers might be used

2024-05-05 12:26 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
ao says it's probably because 6 was the maximum you could reach in any context and if it's too low you wouldn't get the actual reach distance to an entity, so I think what I have currently is correct

2024-05-05 21:24 UTC, Symmettry commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
Alright, is this the same for the place you used 5?

2024-05-05 23:03 UTC, Symmettry commented
Unsure if it's an issue with grim or your pr, but whenever i leave the console is spammed with
[GrimAC] Disconnecting arcaned_ for disconnect.timeout
every single tick

2024-05-05 23:12 UTC, Symmettry commented
Hmm, apparently setting your gravity below around 0.00301 will make you always on ground and then you will not be able to join the server until console changes your gravity. That's weird

2024-05-05 23:15 UTC, Symmettry commented
> Gravity wrongly affects vehicle and stepup seems to be broken

Any gravity above 0.08 seems to do this, and stepup on horses flags.
Is this what you mean by this?

2024-05-08 12:15 UTC, SamB440 commented
> Hmm, apparently setting your gravity below around 0.00301 will make you always on ground and then you will not be able to join the server until console changes your gravity. That's weird

That's normal. 0.003 is the threshold at which movement gets reset to 0.

2024-05-08 12:19 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/RotationPlace.java
> +                Pair<Vector, BlockFace> intercept = ReachUtils.calculateIntercept(box, trace.getOrigin(), trace.getPointAtDistance(distance));
Yes, that seems to just be a magic number limit someone put in

2024-05-08 12:26 UTC, SamB440 commented
I'm not sure what's up with the timed out issue. That's super weird.

2024-05-10 00:40 UTC, Symmettry commented
> I'm not sure what's up with the timed out issue. That's super weird. Client doesn't seem to be sending or receiving any packets from the server
> 
> I think it's possible there's an infinite loop in Grim somewhere, but the question is where
> 
> Edit: Okay yeah the 0.03 vertical handling is looping infinitely due to low gravity

alright cool, I was just hoping that it wasn't my server bugging out lmfao

2024-05-10 00:59 UTC, Symmettry requested changes
It seems good, but if reach distance is at 0 and you use a reach hack to bypass this, you can break blocks right next to you & grim won't flag.
In vanilla, at 0 distance you can't break anything, even right up against your eye, but this bugs out in grim and lets you do it without flags.

2024-05-10 01:00 UTC, Symmettry commented
Actually wait is this prevented in grim or just paper? I don't seem to verbose flag.

2024-05-10 01:32 UTC, Symmettry commented
Other than that it seems to work fine for all new attributes.

2024-05-10 03:38 UTC, ManInMyVan commented
> It seems good, but if reach distance is at 0 and you use a reach hack to bypass this, you can break blocks right next to you & grim won't flag.

Grim doesn't have many breaking checks

2024-05-10 08:37 UTC, SamB440 commented
There's a farplace but there is no farbreak check. Would need to be another pr

2024-05-10 11:48 UTC, SamB440 commented
lgtm, final chance for people to give input.

2024-05-11 01:39 UTC, merged