Add option to ignore duplicate packet rotations
GrimAnticheat/Grim pull request #1558
Opened 2024-06-20 21:43 UTC by ManInMyVan

closes #1557

2024-06-20 23:32 UTC, xEcho1337 commented
That would also fix the no look scaffold, way better than my original patch

2024-06-21 09:05 UTC, SamB440 requested changes

2024-06-21 09:05 UTC, SamB440 commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            handleFlying(player, pos.getX(), pos.getY(), pos.getZ(), ignoreRotation ? player.xRot : pos.getYaw(), ignoreRotation ? player.yRot : pos.getPitch(), flying.hasPositionChanged(), flying.ha
Why is this changed?

2024-06-21 09:05 UTC, SamB440 commented on src/main/resources/config/en.yml
> +# Weather or not to ignore the rotation in duplicate packets
```suggestion
# Whether or not to ignore the rotation in duplicate packets
```

2024-06-21 14:47 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            handleFlying(player, pos.getX(), pos.getY(), pos.getZ(), ignoreRotation ? player.xRot : pos.getYaw(), ignoreRotation ? player.yRot : pos.getPitch(), flying.hasPositionChanged(), flying.ha
We handle the packet even if it's a duplicate, changing the players rotations.

I could do this in handleFlying if you want.

2024-06-21 15:03 UTC, SamB440 commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            handleFlying(player, pos.getX(), pos.getY(), pos.getZ(), ignoreRotation ? player.xRot : pos.getYaw(), ignoreRotation ? player.yRot : pos.getPitch(), flying.hasPositionChanged(), flying.ha
Looking at it again, it makes more sense, we need to cache the config checks though

2024-06-21 16:10 UTC, SamB440 approved these changes

2024-06-22 14:33 UTC, merged