PacketOrder check catagory
GrimAnticheat/Grim pull request #1678
Opened 2024-08-22 17:13 UTC by ManInMyVan

doesn't add any new checks

2024-10-14 16:02 UTC, overkidding commented
I think you forgot to register PacketOrderL?

2024-11-19 12:04 UTC, overkidding commented
PacketOrderI falses "place/use" while hitting a block and right clicking with 1.7 Visuals of  lunar client

2024-12-31 17:52 UTC, SamB440 requested changes
You seem to have removed Post from punishments files and TransactionOrder

2024-12-31 18:36 UTC, ManInMyVan commented
> You seem to have removed Post from punishments files and TransactionOrder

Post was fixed in the rebase, and TransactionOrder was renamed to PacketOrderD, if you don't agree with this rename I'll undo it

2024-12-31 21:24 UTC, SamB440 commented
Yeah I don't agree with renaming transaction order. PacketOrderD doesn't make it clear what it is and using transaction order saves us a letter.

2025-02-19 22:01 UTC, overkidding commented
False Flags Found
- Go near to a cactus and get damage next start spamming sprint and hit the cactus (fast & multiple times)
- Go near to a cactus and get damage next start spamming sprint and swap items in the offhand (fast by holding the swap keybind)
- Go near to a cactus and get damage next start spamming sprint and right click (butterfly click on the cactus)

2025-02-20 01:54 UTC, ManInMyVan commented
> Go near to a cactus and get damage next start spamming sprint and hit the cactus (fast & multiple times)
> Go near to a cactus and get damage next start spamming sprint and swap items in the offhand (fast by holding the swap keybind)
> Go near to a cactus and get damage next start spamming sprint and right click (butterfly click on the cactus)
> Build a 1x1 box, get some sand and a fast shovel spam sand above you (let it fall down) and break it do it fast and multiple times
> Spam shift and right click on an entity (possibly a player)
> Spam shift and attack an entity (possibly a player)
> Attack and right click at the same time on an entity (possibly a player)

can't replicate

> Spam click on a player and do a fast rotation to a block hit it than hit the player back again (multiple times)

not quite sure what this means, but considering none of the other ones worked, I'm going to assume this one doesn't either
 
> Client: 1.21.4

**Vanilla** 1.21.4?

2025-02-20 14:56 UTC, overkidding commented
> **Vanilla** 1.21.4?

Lunar 1.21.4

2025-02-20 14:56 UTC, overkidding commented
> can't replicate

Strange was using Purpur 1.21.4

2025-04-26 22:02 UTC, merged