Permission Load Fix
GrimAnticheat/Grim pull request #1706
Opened 2024-09-10 07:40 UTC by overkidding

When i created the Checks Command PR i actually encountered an error and when i joined the server the "exempted" variable in the check was never true and i fixed it by checking every pollData the permissions for all the checks.

2024-09-12 14:08 UTC, SamB440 commented
Can you fix the spacing formatting?

2024-09-13 03:43 UTC, ManInMyVan requested changes

2024-09-13 03:43 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/player/GrimPlayer.java
> +                .forEach(Check::updateExempted));
Do not cast without checking
```suggestion
        FoliaScheduler.getAsyncScheduler().runNow(GrimAPI.INSTANCE.getPlugin(), t ->
            for (AbstractCheck check : checkManager.allChecks.values()) {
                if (check instanceof Check) {
                    ((Check) check).updateExempted();
                }
            }
        );
```

2024-09-13 03:43 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/Check.java
> +        if(player.bukkitPlayer == null || checkName == null) return;
```suggestion
        if (player.bukkitPlayer == null || checkName == null) return;
```

2024-09-13 03:43 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/Check.java
> +                t -> exempted = player.bukkitPlayer != null && player.bukkitPlayer.hasPermission("grim.exempt." + checkName.toLowerCase()),
You already checked if bukkitPlayer was null
```suggestion
                t -> exempted = player.bukkitPlayer.hasPermission("grim.exempt." + checkName.toLowerCase()),
```

2024-09-13 03:43 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/Check.java
> +                ()->{});
```suggestion
                () -> {});
```

2024-09-14 02:04 UTC, ManInMyVan requested changes

2024-09-14 02:04 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/Check.java
> +    public void updateExempted(){
```suggestion
    public void updateExempted () {
```

2024-09-14 02:11 UTC, ManInMyVan commented
I think we should also remove spaces from check names, otherwise we get things like `grim.exempt.timer - vehicle`, which can't be be given with luckperms in-game.

2024-09-14 05:18 UTC, ManInMyVan requested changes

2024-09-14 05:18 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/Check.java
> +    public void updateExempted () {
I added a space here for some reason, oops
```suggestion
    public void updateExempted() {
```

2024-09-14 15:40 UTC, ManInMyVan approved these changes

2024-09-28 22:30 UTC, merged