Allow exempting elytras
GrimAnticheat/Grim pull request #1715
Opened 2024-09-11 22:28 UTC by ManInMyVan

https://discord.com/channels/811396969670901800/1267889161629864101/1283298260626182226

2024-12-01 18:58 UTC, SamB440 requested changes

2024-12-01 18:58 UTC, SamB440 commented on src/main/java/ac/grim/grimac/predictionengine/MovementCheckRunner.java
> +        } else if (player.disableGrim || (PacketEvents.getAPI().getServerManager().getVersion().isNewerThanOrEquals(ServerVersion.V_1_8) && player.gamemode == GameMode.SPECTATOR) || player.isFlying |
Please add parenthesis to the new and statement to make it clear

2024-12-01 20:39 UTC, ManInMyVan commented
If anyone's wondering why it isn't in the config.yml, I don't want people to enable it because of falses, especially without reporting them

2024-12-03 18:01 UTC, SamB440 approved these changes

2024-12-03 18:01 UTC, merged

2024-12-04 21:04 UTC, ghost commented
Can't read that discord message but if this change is to "patch" false flags when using elytra then I'm not a fan of this

2024-12-05 00:35 UTC, ManInMyVan commented
> Can't read that discord message but if this change is to "patch" false flags when using elytra then I'm not a fan of this

anarchy server wanted to allow elytra fly

2024-12-06 13:22 UTC, ghost commented
> > Can't read that discord message but if this change is to "patch" false flags when using elytra then I'm not a fan of this
> 
> anarchy server wanted to allow elytra fly

ah okay