Add full Japanese translations for all GrimAC configuration files
GrimAnticheat/Grim pull request #1724
Opened 2024-09-16 22:39 UTC by K-Lqrs

While running GrimAC, I noticed that the system logs showed an "Unknown user language JA" message, indicating that Japanese (JA) translations are missing. As a native Japanese speaker and a regular user of GrimAC, I decided to contribute by adding Japanese translations to make the plugin more accessible for Japanese server administrators.

### Changes:
- Added Japanese translations for all GrimAC configuration files, including:
  - Alerts settings
  - Punishments settings
  - Command descriptions
  - Violation messages

These changes do not affect the core functionality of GrimAC, but aim to improve usability for Japanese-speaking users.

Please feel free to review and suggest any modifications if necessary.

2024-09-17 03:17 UTC, matsu1213 requested changes
Please improve unnatural expressions by machine translation.

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # これは、ブランドが以下の正規表現と一致する場合、オペレーターにそのブランドをブロードキャストしないことを意味します
I think "op" or "opプレイヤー" sounds more nutural than "オペレーター".

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# 重複した移動パケットをキャンセルする必要がありますか？
キャンセルする必要がありますか？→キャンセルしますか？

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# Mojangは1.21でこの問題を修正しました。これは "bucket desync" を修正しようとした彼らの試みでした。 https://bugs.mojang.com/browse/MC-12363
→ 1.21でこの問題は修正されました。重複パケットの問題は、Mojangが「バケツの同期ズレ」を修正しようとしたことに起因するものでした。 https://bugs.mojang.com/browse/MC-12363

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # プレイヤーが正当な場合、総アドバンテージをどれだけ乗算する必要がありますか
"正当" might sound a bit unnatural. Maybe we should keep 'legit' as is in English.
or maybe "プレイヤーがチートを使用していない場合" could work as well.
必要がありますか→しますか

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # 1.8の高速使用や高速回復、高速弓バイパスを可能にする場合があるため、120ミリ秒が良いバランスです
fast use/fast heal/fast bow
Module names should not be translated.

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # タイマーバランスを制限し、不正利用を防ぐためのピン値
タイマーバランス→ timerバランス or timer balance
不正利用→乱用
ピン値 → Ping値

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # 無効にしてもチーターを捕まえることができ、誤検知も発生しません
捕まえる→検出する

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# Grimはタイマーのような違法なパケットをキャンセルすることがありますが、1秒間にキャンセルされたパケット数がXを超えた場合、
タイマー→Timer
違法な→不正な

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# これにより、遅延の高いプレイヤーが1つのファイアワークブーストでエリトラを永久に使用するのを防ぎます。
ファイヤーワークブースト→ロケット花火の加速

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # Mojangはエリトラの開始をクライアント側、終了をサーバー側で処理するため、ネットコードが乱れました
処理するため、ネットコードが乱れました→処理することで、ネットコードを台無しにしました

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # プロトコルの変更や制限が原因です。このチェックは、1.7/1.8クライアントで1.8サーバー上で最も効果的です。
プロトコルの変更や制限により、1.9から1.18.1（1.18.2は含まれません）や一部のクライアント/サーバーの組み合わせで0.03の強制的な拡張が発生します。
このチェックは、1.8サーバー上の1.7/1.8クライアントで最も強力です。

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # 目標は1.005のタイマー
→ 1.005 Timerをターゲットにする

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # プレイヤーが正当な場合に、総アドバンテージにどれだけの倍率を掛けますか？
"正当" might sound a bit unnatural. Maybe we should keep 'legit' as is in English.
or maybe "プレイヤーがチートを使用していない場合" could work as well.

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# 他のアンチチートよりもはるかに安定していますが、もし誤検知があれば報告してください。ここで多くのネットコードの問題を修正しました。
多くの→大量の

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # Optifineに対応するために三角関数のテーブルを切り替えて計算していますが、この値を0.001にするとFastMathの影響を軽減できます。
FastMath → FastMath（計算の最適化）

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # 正当なプレイヤーにもセットバックを引き起こす可能性がありますが、このピン値を超えた場合にのみ影響します
"正当" might sound a bit unnatural. Maybe we should keep 'legit' as is in English.
or maybe "プレイヤーがチートを使用していない場合" could work as well.

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # 正当なプレイヤーにもセットバックを引き起こす可能性がありますが、このピン値を超えた場合にのみ影響します
ピン値 → Ping値

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# Grimは、飛行状態を解除されたプレイヤーがXミリ秒以上のピンを持つことを許可しません
ピン→Ping

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# プレイヤーからファイアワークブーストを削除する際の最大ピン値
ファイヤーワークブースト→ロケット花火の加速
ピン値 → Ping値

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # エリトラでスプリントジャンプをすると非常に高い速度を得られます。これをfalseに設定すると、そのエクスプロイトを防ぎます
スプリント → ダッシュ
高い速度を得られます→高い速度になります

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # ゴーストブロック上にプレイヤーが配置されるのを同期して修正するオプションです
このオプションは、ゴーストブロックが発生したときにプレイヤーを再同期させることで、ゴーストブロックへのブロック設置をできるだけ制限します

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +# この設定は、1.17-1.20.5クライアントが1.8サーバーでのみ適用されます。
この設定は、1.8サーバー上の1.17-1.20.5クライアントにのみ適用されます。

2024-09-17 03:17 UTC, matsu1213 commented on src/main/resources/config/ja.yml
> +  # プレイヤーが遅れているときに、後で使用できるよう蓄積できるミリ秒数
遅れているとき→遅れをとったときに

2024-11-01 16:29 UTC, SamB440 commented
Status?

2024-11-02 04:14 UTC, K-Lqrs commented
I'm now making corrections one at a time.

2024-11-02 06:11 UTC, K-Lqrs commented
Correction completed. Please let me know if there are other areas that need to be corrected.

2024-11-25 03:49 UTC, Axionize commented
@ManInMyVan @MachineBreaker @AoElite is there any reason this has been languishing here unmerged?

2024-11-25 15:29 UTC, merged