All HitBox and CollisionBox Changes made for LineOfSightPlace
GrimAnticheat/Grim pull request #1725
Opened 2024-09-17 08:09 UTC by Axionize

As requested by Cotander, I've made a separate PR for all changes made that affect the simulation engine (Hitbox and CollisionBox changes, mostly)

2024-09-23 23:48 UTC, Axionize commented
Currently out of date, need to backport some changes made for LOSP.

2024-09-25 05:34 UTC, Axionize commented
This branch is now up to date with all simulation-related (hitbox and collisionbox) bugfixes and changes made while writing LOSP. Feel free to review and merge

2024-09-30 05:44 UTC, ManInMyVan requested changes

2024-09-30 05:44 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> -    }, StateTypes.LEVER),
These should be moved to `NO_COLLISION`

2024-09-30 05:44 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
>      }, StateTypes.PUMPKIN_STEM, StateTypes.MELON_STEM),
Same as above

2024-10-03 02:40 UTC, ManInMyVan requested changes

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/blocks/connecting/DynamicCollisionWall.java
> +    // Deprecated in favor of DynamicHitboxWall
Remove this method if we aren't using it anywhere, or mark it `@Deprecated`
```suggestion
    /**
     * @deprecated use DynamicHitboxWall
     */
    @Deprecated
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/HitboxData.java
> +            BlockTags.TALL_FLOWERS.getStates().toArray(new StateType[0])),
```suggestion
    TALL_FLOWERS(new SimpleCollisionBox(0, 0, 0, 1, 1, 1, true), BlockTags.TALL_FLOWERS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +            BlockTags.RAILS.getStates().toArray(new StateType[0])),
```suggestion
    RAILS(NoCollisionBox.INSTANCE, BlockTags.RAILS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
>      }, BlockTags.CORALS.getStates().toArray(new StateType[0])),
```suggestion
    CORAL_FAN(new HexCollisionBox(2.0D, 0.0D, 2.0D, 14.0D, 4.0D, 14.0D), BlockTags.CORALS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +            BlockTags.BANNERS.getStates().toArray(new StateType[0])),
```suggestion
    BANNER(NoCollisionBox.INSTANCE, BlockTags.BANNERS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
>              BlockTags.SMALL_FLOWERS.getStates().toArray(new StateType[0])),
```suggestion
    SMALL_FLOWER(NoCollisionBox.INSTANCE, BlockTags.SMALL_FLOWERS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +            BlockTags.TALL_FLOWERS.getStates().toArray(new StateType[0])),
```suggestion
    TALL_FLOWER(NoCollisionBox.INSTANCE, BlockTags.TALL_FLOWERS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +            BlockTags.SAPLINGS.getStates().toArray(new StateType[0])),
```suggestion
    SAPLING(NoCollisionBox.INSTANCE, BlockTags.SAPLINGS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +    }, BlockTags.BUTTONS.getStates().toArray(new StateType[0])),
```suggestion
    BUTTON(NoCollisionBox.INSTANCE, BlockTags.BUTTONS.getStates().toArray(new StateType[0])),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +    // All states that unconditionally have no collision and are not in a group where ever member also has no collision.
"ever member" doesn't make sense, did you mean "every member"?

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/HitboxData.java
> +                throw new RuntimeException("Impossible Banner Facing State; Something very wrong is going on");
imo `RuntimeException` should be replaced with something else like `IllegalStateException` or `IllegalArgumentException`

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/HitboxData.java
> +            StateTypes.REDSTONE_WIRE),
```suggestion
    // Easier to just use no collision box
    // Redstone wire is very complex with its collision shapes and has many de-syncs
    REDSTONE_WIRE(NoCollisionBox.INSTANCE, StateTypes.REDSTONE_WIRE),
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/HitboxData.java
> +            return new SimpleCollisionBox(0.5F - var1, 0.0F, 0.5F - var1, 0.5F + var1, 0.8F, 0.5F + var1);
```suggestion
            return new SimpleCollisionBox(0.1F, 0.0F, 0.1F, 0.9F, 0.8F, 0.9F);
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/HitboxData.java
> +            return new HexOffsetCollisionBox(data.getType(),7.0, getPropaguleMinHeight(data.getAge()), 7.0, 9.0, 16.0, 9.0);
```suggestion
            return new HexOffsetCollisionBox(data.getType(), 7.0, getPropaguleMinHeight(data.getAge()), 7.0, 9.0, 16.0, 9.0);
```

2024-10-03 02:40 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/HitboxData.java
> +        throw new RuntimeException("Impossible State");
imo `RuntimeException` should be replaced with something else like `IllegalStateException` or `IllegalArgumentException`

2024-10-03 05:19 UTC, ManInMyVan requested changes

2024-10-03 05:19 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/math/GrimMath.java
> +        return l >> 16;
This should return the same result (test this)
You should also rename `l`
```suggestion
        long l = x * 3129871 ^ z * 116129781L ^ y;
        return l * l * 42317861 + l * 11 >> 16;
```

2024-10-03 05:19 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    // If your min/max values are > 1 you should probably check out HexCollisionBox
shouldn't this comment be on the constructor with min/max parameters?

also use javadoc, might need to import `HexCollisionBox` to use `@link`
```suggestion
    /**
     * If your min/max values are > 1 you should probably check out {@link HexCollisionBox}
     */
```

2024-10-03 07:45 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/math/GrimMath.java
> +        return l >> 16;
I left it in original form to make it easier to understand. If that's not desired I will make this as short and efificent as possible.

This will also not work. You need to cast to long for ^

2024-11-14 15:57 UTC, merged

2024-11-15 05:12 UTC, Axionize commented
Thank you Sam and ManInMyVan. I apologize for the massive commit but the lack of foresight into the size of the changes required to make this work and a stacked diff system kind of forced my hand.