Optimizing getPossibleEyeHeights()
GrimAnticheat/Grim pull request #1732
Opened 2024-09-22 00:43 UTC by Axionize

This PR makes getPossibleEyeHeights() return double[] and in Standing -> Sneaking -> Elytra order, which is far more likely, reducing the number of average iterations taken in practice to process these checks. In addition, there's no reason to use the list object over the more efficient primitive type, which this PR also changes.

getPossibleEyeHeights() is called for 5 checks in the current codebase. In most cases, its return values are iterated over in a loop to verify some player behavior's like reach or block placement is legitimate. In each of these cases it is far more likely that the player is standing than say flying on an elytra or swimming and hitting an entity.

2024-09-22 05:41 UTC, AoElite commented
You could just cache the list/array. It would need to be recalculated if the scale changes though.

2024-09-22 20:48 UTC, Axionize commented
The thought crossed my mind but I saw the scale being changed and I wasn't sure how to propagate that change in a latency-compensated way if I cached the array.

2024-09-22 21:31 UTC, Axionize commented
I've cached what I can and added additional checks to see if the player is gliding, swimming, or sneaking and returning a different away for this cases.

2024-09-23 04:45 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/player/GrimPlayer.java
>          }
This can be one line
```suggestion
        return this.isSneaking ? possibleEyeHeights[1] : possibleEyeHeights[0];
```

2024-09-23 07:53 UTC, Axionize commented on src/main/java/ac/grim/grimac/player/GrimPlayer.java
>          }
Appreciate it. Do you have any ideas on how I can go about detecting changes to scale and caching it efficiently?

2024-09-24 01:15 UTC, Axionize commented
I've handled changing the array when scale changes with a setRewriter. However while making these changes I've come across 1 major and 2 minor concerns.

**We don't check when the player is crawling**? As usual the code still works for this case but LOSP goes through 42 iterations whenever a player is crawling. If we can add some kind of check for when the player is crawling (doesn't have to be tick-perfect, just good enough and right-enough most of the time we can make it only have to do 1 iteration most of the time, like for every other case).


- 1.14 and below in the original code references a scale attribute, which is the version it was added in, yet player's couldn't have their scale changed until 1.20.5 and the attribute handler rejects changes for < 1.20.5. Why does the possibleEyeHeights array bother checking scale between 1.14 and 1.20.5? It shouldn't have any big cost but its confusing to see nonetheless, shouldn't we only bother dealing with scale for eye height calculations in 1.20.5?

- setRewriter seems to be called more often than it needs to be. I haven't investigated the cause deeply but it seems strange.

2024-09-24 01:38 UTC, Axionize commented
Update: Vanilla's isCrawling() function just returns isSwimming && !touchingWater

If we go vanilla's route we may made need to rethink how we treat isSwimming, especially in simulation.

2024-09-24 07:10 UTC, SamB440 requested changes
You should get the attribute on GrimPlayer and do the set rewriter there. Currently you are doing it for every entity.

2024-09-25 04:44 UTC, Axionize commented
Tested on 1.8 and 1.21. Everything works. LOSP gets the correct ray on the first iteration basically everytime, effectively making LOSP O(1).

In summary, I believe this PR in its current form is ready for merging. 

For future todos, the only thing would be to fix ViaVersion/ViaRewind/ViaBackwards to deal with legacy players who have scales that aren't 1.

I discovered that ViaVersion doesn't handle a player joining on 1.21 -> changing scale -> joining on legacy version very well. We also flagged simulation a ton. I changed the attribute setWriter to accommodate this and most of the instant simulation falses were fixed. Nevertheless via veresion still have issues that persist without grimac being installed

2024-09-25 08:48 UTC, SamB440 requested changes

2024-09-25 08:48 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java
> +                // And then rejoins on old version
This doesn’t make sense, the attribute only changes if the player is on a valid version supporting the attribute

2024-09-25 08:50 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java
> +                // And then rejoins on old version
Oh it’s because you are overriding the required version set rewriter. Simply return the old value instead and don’t expose default value.

2024-09-26 20:02 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java
> +                // And then rejoins on old version
I'm not sure what you're talkinga bout. withSetRewriter looks like this
```
public ValuedAttribute withSetRewriter(BiFunction<Double, Double, Double> rewriteFunction) {
        this.setRewriter = rewriteFunction;
        return this;
    }
```
It literally overwrites the setRewriter. There is only one setRewriter on the ValuedAttribute. If I want to change the behaviour of course I have to overwrite it and include the old and new functionality. There is no option to call super.setRewriter.appy()

2024-09-26 20:05 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java
> +                // And then rejoins on old version
The reason this change exists is because returning the oldValue doesn't work. If a player joins the server on 1.21, has their scale changed to 1.5, and then joins on 1.8 grim, disconnecting themselves on 1.21, grim will still think they have a scale of 1.5 and while that's true server-side for their stored attribute, in reality the client behaves like it does on scale 1.

2024-09-26 20:26 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java
> +                // And then rejoins on old version
That makes 0 sense. GrimPlayer sessions aren't persisted. Returning old value will mean it always stays as the default - 1.

2024-09-26 21:10 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java
> +                // And then rejoins on old version
I went back and tested it and your right. I think I might've been testing the wrong running code when hot reloading. Let me fix that.

2024-09-26 21:14 UTC, Axionize commented
@SamB440 Done.  Can you merge this?

2024-09-27 14:33 UTC, SamB440 requested changes

2024-09-27 14:33 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/FarPlace.java
> +        for (double d : possibleEyeHeights) {
How does this impact performance?

2024-09-27 14:33 UTC, SamB440 commented on src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java
> +        double[] possibleEyeHeights = player.getPossibleEyeHeights();
Make it `final`

2024-09-27 14:33 UTC, SamB440 commented on src/main/java/ac/grim/grimac/player/GrimPlayer.java
> +            }
So this just orders by likelihood?

2024-09-27 14:33 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/data/attribute/ValuedAttribute.java
> +import lombok.Getter;
Remove

2024-09-27 14:33 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntity.java
> +import com.github.retrooper.packetevents.manager.server.ServerVersion;
Remove

2024-09-27 14:33 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/nmsutil/ReachUtils.java
> +        for (double eyes : possibleEyeHeights) {
How does this impact performance?

2024-09-28 03:50 UTC, Axionize commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/FarPlace.java
> +        for (double d : possibleEyeHeights) {
If you're asking about the changes made to getPossibleEyeHeights() in general, this PR does a lot. All the functions the functions that checks that call it see 2x-3x speedup in performance since we're hitting the right eye height 99.9% of the time and exiting our loops much earlier.

If you're asking specifically  what declaring a new variable instead of going `for (double d : possibleEyeHeights)` does, is it prevents multiples calls from being made to player.getPossibleEyeHeights(). This creates a small but measurable performance increase for a while until the JVM eventually optimizes getPossibleEyeHeights() at runtime, at which point you need to use `jmh` to tell the difference.

2024-09-28 03:53 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/nmsutil/ReachUtils.java
> +        for (double eyes : possibleEyeHeights) {
See my answer for the same question you asked on FarPlace.ajva above

2024-09-28 03:53 UTC, Axionize commented on src/main/java/ac/grim/grimac/player/GrimPlayer.java
> +            }
Yes

2024-09-28 03:58 UTC, Axionize commented
All requested changes have been made/addressed

2024-09-28 13:03 UTC, MachineBreaker approved these changes
LGTM

2024-10-31 21:54 UTC, SamB440 approved these changes

2024-10-31 21:54 UTC, merged