Add /grim history <player>
GrimAnticheat/Grim pull request #1782
Opened 2024-11-09 23:16 UTC by AbdisKiosk

This PR introduces the possibility to display a player's violations by adding the /grim history <player> command. When triggered, the command will show something like this:
![image](https://github.com/user-attachments/assets/f3f0159a-75ba-46c7-8084-7aada61706ec)

The PR also adds the "[log]" command for punishments.yml, which inserts the violation to the player's history

This change is extremely useful, as it makes it much easier to determine whether or not player is cheating.

2024-11-10 00:32 UTC, Anthony01M commented
I highly recommend using hikaricp for this

2024-11-10 01:33 UTC, ManInMyVan requested changes

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/PunishmentManager.java
> +                            } else if(command.command.equals("[log]")) {
```suggestion
                            } else if (command.command.equals("[log]")) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/Violation.java
> +    private final String vl;
`double`?

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        } catch(SQLException ex) {
```suggestion
        } catch (SQLException ex) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        } catch(SQLException ex) {
```suggestion
        } catch (SQLException ex) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +            if(resultSet.next()) {
```suggestion
            if (resultSet.next()) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        } catch(SQLException ex) {
```suggestion
        } catch (SQLException ex) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +            while(resultSet.next()) {
```suggestion
            while (resultSet.next()) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        if(openConnection == null || openConnection.isClosed()) {
```suggestion
        if (openConnection == null || openConnection.isClosed()) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +            } catch(SQLException ex) {
```suggestion
            } catch (SQLException ex) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        } catch(ClassNotFoundException e) {
```suggestion
        } catch (ClassNotFoundException e) {
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/Violation.java
> +    }
`@Getter`

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +
```suggestion
```

2024-11-10 01:33 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +            for(int i = logs.size() - 1; i >= 0; i--) {
```suggestion
            for (int i = logs.size() - 1; i >= 0; i--) {
```

2024-11-10 05:51 UTC, ManInMyVan requested changes

2024-11-10 05:51 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +                "%prefix% §bFailed §f%check% (x§c%vl%§f) §7%verbose% (§b%timeago% ago§7)");
add these to the default messages configs

2024-11-10 07:42 UTC, ManInMyVan requested changes

2024-11-10 07:42 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +                "%prefix% §bShowing logs for §f%player% (§f%page%§b/§f%maxPages%§b)");
```suggestion
                "%prefix% §bShowing logs for §f%player% (§f%page%§b/§f%maxPages%§f)");
```
I wonder if all white would look better for the page indicator

2024-11-10 07:58 UTC, ManInMyVan requested changes

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +            //Init sqlite
```suggestion
            // Init sqlite
```

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +            int maxPages = (int) Math.ceil((float) logCount / 15);
max log amount per page should be configurable

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        try(
```suggestion
        try (
```

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +            try(
```suggestion
            try (
```

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        try(
```suggestion
        try (
```

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +                                " WHERE uuid = ?"
```suggestion
                        "SELECT COUNT(*) FROM violations WHERE uuid = ?"
```

2024-11-10 07:58 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/ViolationDatabaseManager.java
> +        try(
```suggestion
        try (
```

2024-11-10 10:39 UTC, AbdisKiosk commented
> I highly recommend using hikaricp for this

Why?

2024-11-10 11:03 UTC, AbdisKiosk commented on src/main/java/ac/grim/grimac/manager/log/Violation.java
> +    private final String vl;
For vl?

2024-11-10 17:44 UTC, ManInMyVan requested changes

2024-11-10 17:44 UTC, ManInMyVan commented on src/main/resources/config/en.yml
> +
add this to all of the config files

2024-11-10 17:44 UTC, ManInMyVan commented on src/main/resources/messages/en.yml
> +grim-history-entry: "%prefix% §bFailed §f%check% (x§c%vl%§f) §7%verbose% (§b%timeago% ago§7)"
add these to all of the messages files

2024-11-10 17:48 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/log/Violation.java
> +    private final String vl;
yes

2024-11-10 18:38 UTC, AbdisKiosk commented on src/main/java/ac/grim/grimac/manager/log/Violation.java
> +    private final String vl;
It should be an `int` if anything. I just copied the code from the DiscordManager. I'll change it tomorrow

2024-11-11 06:27 UTC, Dg32z commented
> > I highly recommend using hikaricp for this
> 
> Why?

I think this may enable querying on any server that uses Grim

2024-11-11 06:28 UTC, Dg32z commented
> > > I highly recommend using hikaricp for this
> > 
> > 
> > Why?
> 
> I think this may enable querying on any server that uses Grim

If possible, I strongly recommend synchronizing Violation across different servers (:

2024-11-11 06:55 UTC, AbdisKiosk commented
> > > > I highly recommend using hikaricp for this
> 
> > > 
> 
> > > 
> 
> > > Why?
> 
> > 
> 
> > I think this may enable querying on any server that uses Grim
> 
> 
> 
> If possible, I strongly recommend synchronizing Violation across different servers (:

Using hikaricp doesn't automatically make querying across servers possible. However, I could implement MySQL support pretty easily, but that would require users to have their own MySQL database.

2024-11-11 10:55 UTC, ManInMyVan requested changes

2024-11-11 10:55 UTC, ManInMyVan commented on src/main/resources/messages/en.yml
> +  - "/grim history <player> [page] §f- §7Shows previous alerts the player"
add this to all of the messages files

2024-11-11 18:05 UTC, ManInMyVan requested changes

2024-11-11 18:05 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/violationdatabase/SQLiteViolationDatabase.java
> +        ) {
```suggestion
        try (Connection connection = getConnection()) {
```

2024-11-11 18:07 UTC, ManInMyVan requested changes

2024-11-11 18:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +                "%prefix% §bShowing logs for §f%player% (§f%page%§b/§f%maxPages%§f)");
```suggestion
                "%prefix% &bShowing logs for &f%player% (&f%page%&b/&f%maxPages%&f)");
```

2024-11-11 18:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/commands/GrimHistory.java
> +                "%prefix% §bFailed §f%check% (x§c%vl%§f) §7%verbose% (§b%timeago% ago§7)");
```suggestion
                "%prefix% &bFailed &f%check% (x&c%vl%&f) &7%verbose% (&b%timeago% ago&7)");
```

2024-11-11 23:29 UTC, ManInMyVan requested changes

2024-11-11 23:29 UTC, ManInMyVan commented on gradlew
Why was this changed?

2024-11-12 07:24 UTC, AbdisKiosk commented on gradlew
don't know. i've reverted it now. sorry

2024-11-13 19:51 UTC, Anthony01M commented
did a quick review, you need to add `server` to the schema to be able to handle cross-servers. 
`[%server%] %user% failed %check_name% [%time%]` (simple example I didn't check your placeholders)

2024-11-15 16:20 UTC, AbdisKiosk commented
> did a quick review, you need to add `server` to the schema to be able to handle cross-servers. `[%server%] %user% failed %check_name% [%time%]` (simple example I didn't check your placeholders)

great suggestion, i've added it now

2024-12-17 16:37 UTC, merged

2025-02-22 20:36 UTC, iam-best commented
Yes, please!

2025-02-22 21:52 UTC, ManInMyVan commented
@AbdisKiosk please open a new pull request for this so it can this can be reviewed and merged

2025-02-22 22:51 UTC, iam-best commented
Wait is it merged now and available or not?

2025-02-23 01:28 UTC, ManInMyVan commented
> Wait is it merged now and available or not?

no, axionize accidentally merged this pr instead of the one in his fork, and reverted the merge

2025-02-23 11:21 UTC, iam-best commented
:/

2025-02-23 13:27 UTC, Axionize commented
@iam-best you can get my fork with this feature along with a slew of other improvements that I hope will (eventually) all make their way into Grim here: https://modrinth.com/plugin/lightning-grim-anticheat

2025-02-23 13:29 UTC, iam-best commented
@Axionize thank you so much, just what I needed a simple additional plugin that adds this Feature! :)

2025-02-23 13:30 UTC, iam-best commented
@Axionize do I need to remove grimac or have both?

2025-02-23 13:31 UTC, Axionize commented
LightningGrim is a fork of Grim. Its is not an extension.

Remove upsteram GrimAC from your plugins folder and use only LightningGrim.

2025-02-23 13:33 UTC, iam-best commented
@Axionize ok thanks!

2025-02-23 14:08 UTC, iam-best commented
@Axionize can you maybe add a feature in the future that connects to the DiscordSRV Plugin and everytime someone hacks it pings a user or role if you haven't added it already? Thanks also maybe change that you can also see the logs from all Players at the same time!

2025-02-23 14:11 UTC, Anthony01M commented
Incorrect place to ask for, discordsrv is also heavy to have on your
server, we can easily make it so that the webhook system is much more
advanced than it currently is and takes discord limitations into
consideration and also does what you need.

On Sun, Feb 23, 2025, 4:08 PM French Fries Guy 🍟 ***@***.***>
wrote:

> @Axionize <https://github.com/Axionize> can you maybe add a feature in
> the future that connects to the DiscordSRV Plugin and everytime someone
> hacks it pings a user or role if you haven't added it already? Thanks also
> maybe change that you can also see the logs from all Players at the same
> time!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GrimAnticheat/Grim/pull/1782#issuecomment-2676881166>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AICPHKUOQXFWZ337MQUB4MT2RHI6LAVCNFSM6AAAAABRPSHTT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZWHA4DCMJWGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
> [image: iam-best]*iam-best* left a comment (GrimAnticheat/Grim#1782)
> <https://github.com/GrimAnticheat/Grim/pull/1782#issuecomment-2676881166>
>
> @Axionize <https://github.com/Axionize> can you maybe add a feature in
> the future that connects to the DiscordSRV Plugin and everytime someone
> hacks it pings a user or role if you haven't added it already? Thanks also
> maybe change that you can also see the logs from all Players at the same
> time!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GrimAnticheat/Grim/pull/1782#issuecomment-2676881166>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AICPHKUOQXFWZ337MQUB4MT2RHI6LAVCNFSM6AAAAABRPSHTT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZWHA4DCMJWGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-02-23 14:18 UTC, iam-best commented
@Anthony01M if you have alternative plugins you can DM them me of reply here then :)

2025-02-23 14:21 UTC, Anthony01M commented
None, simply use the webhook system already built-in, that's good enough,
instead of adding more load on your server.

On Sun, Feb 23, 2025, 4:18 PM French Fries Guy 🍟 ***@***.***>
wrote:

> @Anthony01M <https://github.com/Anthony01M> if you have alternative
> plugins you can DM them me of reply here then :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GrimAnticheat/Grim/pull/1782#issuecomment-2676886194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AICPHKULU3KEM7KZUV4AKE32RHKC7AVCNFSM6AAAAABRPSHTT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZWHA4DMMJZGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> [image: iam-best]*iam-best* left a comment (GrimAnticheat/Grim#1782)
> <https://github.com/GrimAnticheat/Grim/pull/1782#issuecomment-2676886194>
>
> @Anthony01M <https://github.com/Anthony01M> if you have alternative
> plugins you can DM them me of reply here then :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GrimAnticheat/Grim/pull/1782#issuecomment-2676886194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AICPHKULU3KEM7KZUV4AKE32RHKC7AVCNFSM6AAAAABRPSHTT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZWHA4DMMJZGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-02-23 14:29 UTC, iam-best commented
@Anthony01M yeah I use it the plugin for other stuff too but how can I do that... Is there a tutorial? If it does the same thing as the Discord Plugin I will remove it but first need an alternative.