Ensure ComplexCollisionBoxes can only contain SimpleCollisionBoxes
GrimAnticheat/Grim pull request #1805
Opened 2024-11-17 16:47 UTC by Axionize

Flattening out ComplexCollisionBoxes reduces complexity and increases performance. Also may allow us to primitize more of this class in the future.

2024-11-20 17:45 UTC, Axionize commented
I will leave optimizing the memory usage of every ComplexCollisionBox as a separate PR after this one gets merged to make review easier.

EDIT: I just merged it into the same PR because it made fixing issues easier.

2024-11-20 22:37 UTC, ManInMyVan requested changes

2024-11-20 22:37 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/RaycastData.java
What's this empty file for?

2024-11-21 11:14 UTC, Cyramek commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +        if (version.isNewerThanOrEquals(ClientVersion.V_1_13)) {
shouldn't maxIndex = 2 be in another if statement? that bug only exists in 1.8

2024-11-21 15:17 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java
> +        if (version.isNewerThanOrEquals(ClientVersion.V_1_13)) {
I was lazy and didn't want to write out another if statement when this was "good enough" and will work anyways. The code won't fail if maxIndex is too big merely use up a little more memory.

I'll trade more memory for faster compute any day of the week.

2024-11-21 15:20 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/collisions/RaycastData.java
It's from LightningGrim and contains data analogous to CollisionData and HitboxData for blocks like Cauldrons, Hoppers, Composters, and Scaffolding which have different hitboxes to calculate the blockface from ray traces, overriding RaycastData.

I emptied it instead of deleting it in the PR, my bad.

2024-11-21 17:07 UTC, Axionize commented
This PR is now complete and as far as I'm aware has no bugs/issues. Can I get a review and merge?

2024-11-21 21:54 UTC, Axionize commented
This PR is now complete and as far as I'm aware has no bugs/issues. Can I get a review and merge?

2024-11-23 10:57 UTC, merged