Fix airliquidplace
GrimAnticheat/Grim pull request #1822
Opened 2024-11-25 03:05 UTC by Axionize

2024-11-25 09:25 UTC, ManInMyVan requested changes

2024-11-25 09:25 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +        This is incredibly rare, unreliable and is only triggerable if you intentionally want to false the check. Enough so that I consider a violation lvl of 2-3 to be reliable and 5-6 to be autoban
```suggestion
    /*
     * This check has been plagued by falses for ages, and I've finally figured it out.
     * When breaking and placing on the same tick in the same tick, I believe the vanilla client always sends DIGGING ACTION packets first
     * This check's falses all seem to stem from processing DiggingAction.START_DIGGING before PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT in the same tick
     * Since we process the break first, when we go to process the place it looks like the player placed against air in the async world
     *
     * We will often see:
     *     Async world updated: short_grass -> air at X: -32, Y: 69, Z: -240, tick 0, cause/source: DiggingAction.START_DIGGING
     *     AirLiquidPlace Check: Block state at X: -32, Y: 69, Z: -240 is air (valid: false), tick +0-1, cause/source: PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT <---- previously falsed here
     *     Async world updated: air -> short_grass at X: -32, Y: 69, Z: -240, tick +3-4, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
     *     Async world updated: short_grass -> air at X: -32, Y: 69, Z: -240, tick +0-1, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
     *
     * In addition, it is possible for:
     *     Async world updated: short_grass -> air at X: -49, Y: 69, Z: -190, tick 0, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
     *     AirLiquidPlace Check: Block state at X: -49, Y: 69, Z: -190 is air (valid=false), tick 0 <--- false due to change from applyBlockChanges()
     *     Async world updated: grass_block[snowy=false] -> grass_block[snowy=false] at X: -49, Y: 69, Z: -189, tick 0, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
     *
     * And in even more rare cases:
     *     Async world updated: air -> air at X: -51, Y: 71, Z: -179, tick 0, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
     *     AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -180 is short_grass (valid=true), tick 0
     *     Async world updated: short_grass -> air at X: -49, Y: 70, Z: -180, tick 1, cause/source: DiggingAction.START_DIGGING <--- double dig here (see my BadPacketsX patch) this is legit behaviour. Can only be up to 2 in 1 tick though.
     *     Async world updated: air -> short_grass at X: -49, Y: 70, Z: -180, tick 1, cause/source: DiggingAction.START_DIGGING
     *     Async world updated: short_grass -> air at X: -51, Y: 70, Z: -179, tick 1, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
     *     AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=false), tick 2 <--- falses here due to double dig if we only check the latest changed blockstate. We have to check all changes at the location in same tick.
     *     AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=true), tick 2
     *
     *     All of which previously would've caused a false.
     *     To solve this we store recently changed blocks caused by DiggingAction.START_DIGGING (instant breaking) and check against the old block.
     *     Lots of other checks have similar issues, and with the new player.blockHistory we can patch those.
     *
     * So that's it right? It's unfalsable?
     *     Very close but not quite. Vanilla's client game desyncs, especially on a laggy connection where a player is breaking and placing grass 20 cps/sec in the same tick
     *     it is possible for short grass to be interacted with even if server-side the block is air much later, and it won't be accounted for because the modification isn't recent.
     *     This is incredibly rare, unreliable and is only triggerable if you intentionally want to false the check. Enough so that I consider a violation lvl of 2-3 to be reliable and 5-6 to be autobannable
```

2024-12-02 12:02 UTC, SamB440 commented
CheckManagerlistener still has conflicts

2024-12-02 22:15 UTC, Axionize commented
Yes I'll fix this when we resolve https://github.com/GrimAnticheat/Grim/pull/1846 since it modifies similar lines.

2024-12-08 22:49 UTC, Axionize commented
I've rebased it @SamB440

2024-12-08 23:10 UTC, ManInMyVan requested changes

2024-12-08 23:10 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
```suggestion
```

2024-12-08 23:10 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +
```suggestion
```

2024-12-12 20:46 UTC, Axionize commented
I'll take care of this in a couple days; been pretty busy.

2024-12-15 22:00 UTC, Axionize commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
Done

2024-12-15 22:00 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +
Done

2024-12-15 22:01 UTC, Axionize commented
I'll merge this myself, just need someone else to give it a review and make sure everything's ready.

2024-12-16 07:31 UTC, ManInMyVan requested changes

2024-12-16 07:31 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/BlockModification.java
> +//    private final long time; // System time in milliseconds or nanoseconds for ordering
```suggestion
```

2024-12-16 07:31 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
```suggestion
```

2024-12-16 21:18 UTC, Axionize commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
I want separate the early return from the rest of the code via whitespace, I think it makes sense.

2024-12-16 21:23 UTC, Axionize commented
@ManInMyVan any other suggestions before I merge?

2024-12-16 23:07 UTC, ManInMyVan requested changes

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +    // Clear all block modifications
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +    // Add a new block modification to the history.
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +    // Get the size of the block history
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +    // Get all recent modifications (optionally filtered by a condition).
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +    // Remove old modifications older than maxTick
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
```suggestion
```

2024-12-16 23:07 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
```suggestion
```

2024-12-17 04:40 UTC, Axionize commented
Ok I think that's everything, one last time @ManInMyVan do you approve?

2024-12-17 04:59 UTC, ManInMyVan requested changes

2024-12-17 04:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +
```suggestion
```

2024-12-17 04:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +    /*
```suggestion

    /*
```

2024-12-17 04:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java
> +}
```suggestion
}

```

2024-12-17 04:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java
> +            if (!(stateType.isAir() || Materials.isNoPlaceLiquid(stateType))) {
```suggestion
            if (!stateType.isAir() && !Materials.isNoPlaceLiquid(stateType)) {
```

2024-12-18 23:29 UTC, Axionize commented
@ManInMyVan is that it? Anything else? I will squash and merge if you have no objections.

2024-12-18 23:40 UTC, ManInMyVan approved these changes

2024-12-19 03:21 UTC, merged