Fix Modern Client + Legacy Server Walls
GrimAnticheat/Grim pull request #1824
Opened 2024-11-25 04:56 UTC by Axionize

Closes: https://github.com/GrimAnticheat/Grim/pull/1107 https://github.com/GrimAnticheat/Grim/issues/928 https://github.com/GrimAnticheat/Grim/issues/1459

Also Improves performance of DynamicCollisionWall.fetch() measurably

2024-11-25 05:23 UTC, ManInMyVan requested changes

2024-11-25 05:23 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/collisions/blocks/connecting/DynamicCollisionWall.java
> +        Lead to simulation falses. Fixing this rare edge case requires lots more effort than worth and is low priority
```suggestion
     * This implementation together with the simulation engine have some limitations.
     * Running into/being knocked into corner walls on a legacy server on a modern client and vice versa
     * Lead to simulation falses. Fixing this rare edge case requires lots more effort than worth and is low priority
```

2024-12-01 01:00 UTC, SamB440 requested changes

2024-12-01 01:00 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/DynamicCollisionBox.java
> +//    @Override
Why!?

2024-12-01 01:00 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    public CollisionBox encompass(SimpleCollisionBox other) {
Why change the name?

2024-12-01 01:00 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    public CollisionBox union(SimpleCollisionBox other) {
Huh? What’s this do now?

2024-12-01 04:48 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    public CollisionBox union(SimpleCollisionBox other) {
union() actually unions the boxes into an object that includes both the existing and other box. This is different from encompass() which is SCB specific and combines the two SCBs into one new SCB that encompasses both (and potentially more space)

2024-12-01 04:49 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/DynamicCollisionBox.java
> +//    @Override
I'll fix

2024-12-01 04:59 UTC, Axionize commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    public CollisionBox encompass(SimpleCollisionBox other) {
It is no longer the same method. See below.

2024-12-01 11:04 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    public CollisionBox union(SimpleCollisionBox other) {
Why change the push handler to use this then?

2024-12-01 13:22 UTC, SamB440 commented on src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java
> +    public CollisionBox union(SimpleCollisionBox other) {
Nvm am dum

2024-12-09 06:06 UTC, SamB440 approved these changes

2024-12-09 06:15 UTC, ManInMyVan approved these changes

2024-12-15 22:12 UTC, merged

2024-12-16 20:31 UTC, ghost commented
wall collision is also broken for modern clients on modern version (no viaversion) see #1884