1.21.3 update
GrimAnticheat/Grim pull request #1831
Opened 2024-11-27 17:07 UTC by SamB440

- Added support for 1.21.3 vehicles
- Added support for new end tick packet
- Added support for new player input packet
- Fixed precision loss when jumping and/or in the air (we are now 1e-15 average)

~~For some reason, sneaking whilst sprinting falses on 1.21.3, yet the movement is the same as older versions. Someone needs to figure out the issue there.~~

ViaVersion setups are not supported and will not be supported until we have the ability to bypass via for certain listeners.

Fixes #1769 
Closes #1702

2024-11-28 01:30 UTC, ewof commented
```
[01:19:11 WARN]: [GrimAC] Global task for GrimAC v2.3.68 generated an exception
java.lang.IllegalStateException: Async chunk retrieval
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:52) ~[parchment-1.21.3.jar:1.21.3-DEV-0249f75]
        at org.bukkit.craftbukkit.CraftWorld.getChunkAt(CraftWorld.java:371) ~[parchment-1.21.3.jar:1.21.3-DEV-0249f75]
        at grimac-2.3.68.jar/ac.grim.grimac.events.packets.patch.ResyncWorldUtil.lambda$resyncPositions$2(ResyncWorldUtil.java:78) ~[grimac-2.3.68.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[parchment-1.21.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[parchment-1.21.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[parchment-1.21.3.jar:?]
        ```

2024-11-28 20:34 UTC, Cyramek commented
fastbreak should also be updated?

2024-11-29 00:38 UTC, ManInMyVan requested changes

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                forward += 1;
```suggestion
                forward++;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                forward -= 1;
```suggestion
                forward--;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                sideways += 1;
```suggestion
                sideways++;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                sideways -= 1;
```suggestion
                sideways--;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
> +                forwardMin += 1;
```suggestion
                forwardMax++;
                forwardMin++;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
> +                forwardMin -= 1;
```suggestion
                forwardMax--;
                forwardMin--;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
> +                strafeMin += 1;
```suggestion
                strafeMax++;
                strafeMin++;
```

2024-11-29 00:38 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
> +                strafeMin -= 1;
```suggestion
                strafeMax--;
                strafeMin--;
```

2024-12-01 07:59 UTC, ManInMyVan requested changes

2024-12-01 07:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                forward += 1;
```suggestion
                forward++;
```

2024-12-01 07:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                forward -= 1;
```suggestion
                forward--;
```

2024-12-01 07:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                sideways += 1;
```suggestion
                sideways++;
```

2024-12-01 07:59 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java
> +                sideways -= 1;
```suggestion
                sideways--;
```

2024-12-01 15:59 UTC, SamB440 commented
> fastbreak should also be updated?

What should be?

2024-12-01 17:04 UTC, ManInMyVan commented
> > fastbreak should also be updated?
> 
> What should be?

instead of being based on ms, it should be based on ticks, like I did for pre 1.9 clients in my breaking checks pr

2024-12-01 17:10 UTC, SamB440 commented
I don't see anything 1.8-like / specific in fast break. There's only `On 1.8 clients, via screws with this packet meaning we must fall back to the 1.8 idle flying packet`, but we're _meant_ to be using animation packet

2024-12-04 13:37 UTC, merged