Add permission to enable verbose on join
GrimAnticheat/Grim pull request #1833
Opened 2024-11-28 04:55 UTC by Axionize

2024-11-28 05:00 UTC, ManInMyVan commented
Add it to the plugin yml

2024-11-28 19:46 UTC, Axionize commented
Verbose wasn't in the plugin.yml so I chose not to add this one either. Are you certain I should add verbose on join permission to the plugin.yml when the verbose pemrission itself isn't?

2024-11-28 22:23 UTC, ManInMyVan commented
> Verbose wasn't in the plugin.yml so I chose not to add this one either. Are you certain I should add verbose on join permission to the plugin.yml when the verbose pemrission itself isn't?

add both

2024-11-29 02:48 UTC, Axionize commented
What about the gradle buildscript? Alerts and alert on join is likewise in it but verbose is not?

2024-11-29 03:15 UTC, ManInMyVan commented
> What about the gradle buildscript? Alerts and alert on join is likewise in it but verbose is not?

add verbose then?

2024-11-30 03:50 UTC, Axionize commented
Supersedes and includes https://github.com/GrimAnticheat/Grim/pull/1840

2024-11-30 03:54 UTC, ManInMyVan requested changes

2024-11-30 03:54 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerJoinQuit.java
> +            }
this shouldn't be inside alerts, alerts perm isn't needed to toggle verbose

2024-12-01 14:46 UTC, merged