Remove Usage of Var
GrimAnticheat/Grim pull request #1846
Opened 2024-12-01 22:19 UTC by Axionize

I'm fine with the final which makes it clear a variable is never modified but not knowing a var type at a glance is terrible.

2024-12-01 23:23 UTC, ManInMyVan requested changes

2024-12-01 23:23 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            final BlockBreak blockBreak = new BlockBreak(packet, player);
I think it's pretty obvious what the type of these are, they use a constructor

2024-12-01 23:52 UTC, Axionize commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            final BlockBreak blockBreak = new BlockBreak(packet, player);
It's consistent with the rest of the code base, and while I can only speak for myself on this front, when I look for the type of something I always first look to the left then right

2024-12-02 00:09 UTC, ManInMyVan approved these changes

2024-12-02 12:01 UTC, SamB440 commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            final BlockBreak blockBreak = new BlockBreak(packet, player);
I don’t see a need to go reverting every var change, using var here makes sense as it shortens the line whilst the type is still clear

2024-12-02 22:12 UTC, Axionize commented on src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java
> +            final BlockBreak blockBreak = new BlockBreak(packet, player);
@MachineBreaker thoughts?

2024-12-04 20:36 UTC, merged

2024-12-04 21:07 UTC, ghost commented
W change, reading code on github with var in it is awful