Add alert bungee messaging
GrimAnticheat/Grim pull request #495
Opened 2022-05-16 22:43 UTC by iFlamingoz

Solves #407

2022-05-19 22:56 UTC, iFlamingoz commented
> Can this be made more proxy-agonistic? BungeeCord isn't the only proxy software that exists, and it looks like this PR is incompatible with velocity in multiple ways.

Velocity has bungee messaging support and I have tested this on velocity.

2022-05-19 23:36 UTC, Jaren8r commented
1. This won't work with velocity modern forwarding as your code is only checking spigot.yml to see if bungeecord is set to true
2. ~~Velocity doesn't emit a PluginMessageEvent for plugin messages on the BungeeCord channel if `bungee-plugin-message-channel` is true, which is a default config option. A separate plugin messaging channel may be better for this.~~
3. ~~If this is supposed to work with multiple proxies, then why name it specifically bungeecord in the config file?~~

Whoops, I'm kind of an idiot. I only half-looked at it and I incorrectly assumed that you would need a companion plugin on your proxy to send the messages. I completely forgot you could use the BungeeCord message to forward messages to other servers.

2022-05-19 23:39 UTC, Jaren8r requested changes

2022-05-19 23:39 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/manager/init/start/PacketManager.java
> +        AlertPluginMessenger.setBungeeEnabled(YamlConfiguration.loadConfiguration(new File("spigot.yml")).getBoolean("settings.bungeecord"));
This isn't compatible with velocity modern forwarding setups.

2022-05-19 23:39 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/events/packets/AlertPluginMessenger.java
> +    @Override
Indentation error

2022-05-19 23:39 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/events/packets/AlertPluginMessenger.java
> +			byte[] msgbytes = new byte[in.readShort()];
Indentation error

2022-05-19 23:39 UTC, Jaren8r commented on src/main/resources/config/en.yml
> +     # Should alerts received by other servers be broadcasted?
```suggestion
     # Should alerts received from other servers be broadcasted?
```

2022-06-28 06:51 UTC, NoJokeFNA requested changes

2022-06-28 06:51 UTC, NoJokeFNA commented on src/main/java/ac/grim/grimac/commands/GrimSendAlert.java
> +        	ProxyAlertMessenger.sendPluginMessage(string);
Add more spaces:
```java
        if (ProxyAlertMessenger.canSendAlerts()) {
            ProxyAlertMessenger.sendPluginMessage(string);
```

2022-06-28 06:51 UTC, NoJokeFNA commented on src/main/java/ac/grim/grimac/events/packets/ProxyAlertMessenger.java
> +
Why soo many empty spaces? Remove the useless ones

2022-10-16 21:35 UTC, merged

2022-10-17 09:28 UTC, caoli5288 commented
Can it support multi-bungee?

2022-10-17 12:58 UTC, iFlamingoz commented
> Can it support multi-bungee?

I am not sure.