Support for MultiPaper and Geyser
GrimAnticheat/Grim pull request #531
Opened 2022-06-03 17:07 UTC by modern158

2022-06-28 06:43 UTC, NoJokeFNA requested changes

2022-06-28 06:43 UTC, NoJokeFNA commented on src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java
> +
Remove this empty line

2022-06-28 06:43 UTC, NoJokeFNA commented on src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java
> +
Remove this empty line

2022-07-06 04:35 UTC, PureGero commented on src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java
> +
This change is already merged btw
https://github.com/MWHunter/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java

2022-07-06 04:36 UTC, PureGero commented on src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java
> +
This change is already merged btw
https://github.com/MWHunter/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java

2022-07-06 20:16 UTC, closed without merging