WIP: Inventory Checks
GrimAnticheat/Grim pull request #995
Opened 2023-03-18 20:31 UTC by MachineBreaker

After some people proposed adding inventory checks to GrimAC, I have decided to contribute some of them. This is a work in progress.

Ideas are welcome

To-Do List:
- [X] Detect when the player opens the inventory
- [X] 1.7-1.19 Version support
- [] Attack while inventory is open detection
- [] Moving while inventory is open detection

PD: This task list can be updated to add/remove inventory checks.

People actually working on this WIP:
@c0dingnoobi, @MachineBreaker 

Resolves #945

2023-03-19 14:35 UTC, UserNugget commented
I think InventoryD should use prediction instead
You can hook into this part of code: (but it does not work for entities)
https://github.com/GrimAnticheat/Grim/blob/d7c4e07ad122d156f46ee07bb351ccf65b4393ea/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L716-L726
Also, you can check https://github.com/UserNugget/Grim/commit/928617167082bb32f5796af022a9e7973bfab550

2023-03-19 14:52 UTC, MachineBreaker commented
Misclick

2023-03-19 14:53 UTC, MachineBreaker commented
> I think InventoryD should use prediction instead You can hook into this part of code: (but it does not work for vehicles)
> 
> https://github.com/GrimAnticheat/Grim/blob/d7c4e07ad122d156f46ee07bb351ccf65b4393ea/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L716-L726
> 
> 
> Also, you can check [UserNugget@9286171](https://github.com/UserNugget/Grim/commit/928617167082bb32f5796af022a9e7973bfab550)

We can also wait for your prediction inventory walk check to be stable and contributing it in this PR

2023-03-29 12:00 UTC, Perwollnt commented
It would be a great idea to add Extra inventory check (Crafting menu storage).
I dont really know if its possible and i dont see it in any other anticheat.
Also a check to see if the palyer opened his inventory in a nether portal.

2023-03-30 06:44 UTC, MachineBreaker commented
> It would be a great idea to add Extra inventory check (Crafting menu storage). I dont really know if its possible and i dont see it in any other anticheat. Also a check to see if the palyer opened his inventory in a nether portal.

If you want to give ideas, give it properly please, i don't know what means Crafting menu storage inventory check, and how we know the player didn't opened the inventory in the air then joined the portal? however, doing that gives 0 advantage

2023-03-30 17:27 UTC, Perwollnt commented
> > It would be a great idea to add Extra inventory check (Crafting menu storage). I dont really know if its possible and i dont see it in any other anticheat. Also a check to see if the palyer opened his inventory in a nether portal.
> 
> If you want to give ideas, give it properly please, i don't know what means Crafting menu storage inventory check, and how we know the player didn't opened the inventory in the air then joined the portal? however, doing that gives 0 advantage

Where can I give ideas?
There is a cheat module that allows you to store items in your crafting slots.
You can check the event(When the player opens an inventory) player's head location. That way they can open their inventory and hop in the portal, and it will only detect players who are cheating.

2023-05-21 15:26 UTC, MachineBreaker commented
@MWHunter Ready for review

2023-05-21 17:11 UTC, AoElite commented
I've already implemented slight variations of these checks into the upcoming Grim 3.0 anticheat. However it's probably fine to merge these into 2.0 with a few changes. I don't think these checks should setback players, but instead just flag & force close their inventory just incase of any desyncs or any unforeseen issues.

2023-05-21 17:14 UTC, MachineBreaker commented
I'll do the changes

2023-05-21 17:21 UTC, MachineBreaker commented
@AoElite It's fine now?

2023-05-22 02:33 UTC, EternalHuman commented
> @AoElite It's fine now?

asynchronous close inventory

2023-05-22 10:09 UTC, MachineBreaker commented
> > @AoElite It's fine now?
> 
> asynchronous close inventory

I don't think i can understand what u mean?

2023-05-22 11:40 UTC, AoElite commented
You can't close the inventory on the netty thread, you have to run it sync.

2023-05-22 11:47 UTC, BigPanda97 commented
> force close their inventory just incase of any desyncs or any unforeseen issues.

Forcing the inventory to close is impossible I guess, because there are already several clients which can ignore such packets and even open the inventory without sending packets.

2023-05-22 12:04 UTC, AoElite commented
> > force close their inventory just incase of any desyncs or any unforeseen issues.
> 
> Forcing the inventory to close is impossible I guess, because there are already several clients which can ignore such packets and even open the inventory without sending packets.

If a client ignores the packet then of course it's impossible to close their inventory. However that's not relevant, it's to resync clients just incase of a desync so they don't flag more. So it'd just harm clients ignoring it. Also, opening your inventory doesn't send a packet in higher versions, that's just vanilla.

2023-05-25 23:33 UTC, MachineBreaker commented
Done @AoElite , should be fine to merge now

2023-05-28 05:38 UTC, AoElite commented
I found some false flags with these checks when testing on a server. I'm looking into how to replicate.

2023-06-18 22:16 UTC, overkidding commented
If a player sprints or jumps and instantly after opens an inventory it gets closed.

2023-06-19 02:19 UTC, MachineBreaker commented
> If a player sprints or jumps and instantly after opens an inventory it gets closed.

Prediction code might be still running in that case, that's all what i can think about

2023-06-19 07:32 UTC, UserNugget commented
> If a player sprints or jumps and instantly after opens an inventory it gets closed.

Cannot reproduce, what client did you use?
If it flags InventoryD, movements with input have more score over movements without input, so most likely it means that a client still controls movement after inventory got opened

2023-06-20 10:14 UTC, overkidding commented
> > If a player sprints or jumps and instantly after opens an inventory it gets closed.
> 
> Cannot reproduce, what client did you use?
> If it flags InventoryD, movements with input have more score over movements without input, so most likely it means that a client still controls movement after inventory got opened

It works with vanilla and other clients, version 1.8
I mainly used lunar

2023-06-20 10:15 UTC, overkidding commented
> > If a player sprints or jumps and instantly after opens an inventory it gets closed.
> 
> Prediction code might be still running in that case, that's all what i can think about

Yup thats why probably, i added a buffer to the check to make it sure and it works.

2023-06-20 19:17 UTC, MachineBreaker commented
> > > If a player sprints or jumps and instantly after opens an inventory it gets closed.
> > 
> > 
> > Cannot reproduce, what client did you use?
> > If it flags InventoryD, movements with input have more score over movements without input, so most likely it means that a client still controls movement after inventory got opened
> 
> It works with vanilla and other clients, version 1.8 I mainly used lunar

Can you send a video reproducing this? I cannot reproduce with vanilla client

2023-06-23 08:59 UTC, overkidding commented
> 

Ok let me record and upload it

2023-06-23 09:07 UTC, overkidding commented
> > > > If a player sprints or jumps and instantly after opens an inventory it gets closed.
> > > 
> > > 
> > > Cannot reproduce, what client did you use?
> > > If it flags InventoryD, movements with input have more score over movements without input, so most likely it means that a client still controls movement after inventory got opened
> > 
> > 
> > It works with vanilla and other clients, version 1.8 I mainly used lunar
> 
> Can you send a video reproducing this? I cannot reproduce with vanilla client

There it is https://youtu.be/RQUluYOyNMU

2023-06-23 10:41 UTC, UserNugget commented
@overkidding, looks like i did something wrong with movement processing
Can you try to reproduce it with this patch?
```patch
Subject: [PATCH] patch
---
Index: src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java b/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
--- a/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java	(revision f699be1a65240c576ff07c6abe394bc561cad5f7)
+++ b/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java	(date 1687516170819)
@@ -105,6 +105,7 @@
 
         double bestInput = Double.MAX_VALUE;
 
+        VectorData withoutInput = null, withInput = null;
         VectorData bestCollisionVel = null;
         Vector beforeCollisionMovement = null;
         Vector originalClientVel = player.clientVelocity.clone();
@@ -123,7 +124,7 @@
             // Check if this vector could ever possible beat the last vector in terms of accuracy
             // This is quite a good optimization :)
             if (bestTheoreticalCollisionResult.distanceSquared(player.actualMovement) > bestInput && !clientVelAfterInput.isKnockback() && !clientVelAfterInput.isExplosion()) {
-                continue;
+                // continue; // force process every movement
             }
 
             if (clientVelAfterInput.isZeroPointZeroThree()) {
@@ -179,7 +180,12 @@
                 continue;
             }
 
-            if (resultAccuracy < bestInput) {
+            if (resultAccuracy <= bestInput) { // movements with and without input can have same offsets
+                if (!clientVelAfterInput.isWithInput() && !clientVelAfterInput.isJump()) {
+                    withoutInput = clientVelAfterInput;
+                } else {
+                    withInput = clientVelAfterInput;
+                }
                 bestCollisionVel = clientVelAfterInput.returnNewModified(outputVel, VectorData.VectorType.BestVelPicked);
                 bestCollisionVel.preUncertainty = clientVelAfterInput;
                 beforeCollisionMovement = primaryPushMovement;
@@ -193,9 +199,14 @@
 
             // Close enough, there's no reason to continue our predictions (if either kb or explosion will flag, continue searching)
             if (bestInput < 1e-5 * 1e-5 && !player.checkManager.getKnockbackHandler().wouldFlag() && !player.checkManager.getExplosionHandler().wouldFlag()) {
-                break;
+                // break; // force process every movement
             }
         }
+
+        // print "offset" between movements
+        if (withoutInput != null && withInput != null) {
+            System.out.println("input vs without input \"offset\": " + withoutInput.vector.distanceSquared(withInput.vector));
+        }
 
         assert beforeCollisionMovement != null;
 
@@ -454,14 +465,10 @@
             bScore -= 2;
 
         if (a.isWithInput() || a.isJump())
-            aScore += 1;
-        else
-            aScore -= 1;
+            aScore += 20; // over-prioritize movements without input (will cause random falses)
 
         if (b.isWithInput() || b.isJump())
-            bScore += 1;
-        else
-            bScore -= 1;
+            bScore += 20; // over-prioritize movements without input (will cause random falses)
 
         // If the player is on the ground but the vector leads the player off the ground
         if ((player.compensatedEntities.getSelf().inVehicle() ? player.clientControlledVerticalCollision : player.onGround) && a.vector.getY() >= 0)
```

2023-06-23 13:01 UTC, EternalHuman commented
> There it is https://youtu.be/RQUluYOyNMU

![image](https://github.com/GrimAnticheat/Grim/assets/71584363/bb6b312c-de81-41cb-95a7-ba6a450c19c4)

2023-06-23 13:02 UTC, EternalHuman commented
Are you sure you made these changes in PredictionEngine?

2023-06-23 14:05 UTC, overkidding commented
> Are you sure you made these changes in PredictionEngine?

Yup

> > There it is https://youtu.be/RQUluYOyNMU
> 
> ![image](https://user-images.githubusercontent.com/71584363/248274198-bb6b312c-de81-41cb-95a7-ba6a450c19c4.png)

Yup sure

2023-06-23 14:15 UTC, overkidding commented
> @overkidding, looks like i did something wrong with movement processing Can you try to reproduce it with this patch?
> 
> ```diff
> Subject: [PATCH] patch
> ---
> Index: src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java b/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java
> --- a/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java	(revision f699be1a65240c576ff07c6abe394bc561cad5f7)
> +++ b/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java	(date 1687516170819)
> @@ -105,6 +105,7 @@
>  
>          double bestInput = Double.MAX_VALUE;
>  
> +        VectorData withoutInput = null, withInput = null;
>          VectorData bestCollisionVel = null;
>          Vector beforeCollisionMovement = null;
>          Vector originalClientVel = player.clientVelocity.clone();
> @@ -123,7 +124,7 @@
>              // Check if this vector could ever possible beat the last vector in terms of accuracy
>              // This is quite a good optimization :)
>              if (bestTheoreticalCollisionResult.distanceSquared(player.actualMovement) > bestInput && !clientVelAfterInput.isKnockback() && !clientVelAfterInput.isExplosion()) {
> -                continue;
> +                // continue; // force process every movement
>              }
>  
>              if (clientVelAfterInput.isZeroPointZeroThree()) {
> @@ -179,7 +180,12 @@
>                  continue;
>              }
>  
> -            if (resultAccuracy < bestInput) {
> +            if (resultAccuracy <= bestInput) { // movements with and without input can have same offsets
> +                if (!clientVelAfterInput.isWithInput() && !clientVelAfterInput.isJump()) {
> +                    withoutInput = clientVelAfterInput;
> +                } else {
> +                    withInput = clientVelAfterInput;
> +                }
>                  bestCollisionVel = clientVelAfterInput.returnNewModified(outputVel, VectorData.VectorType.BestVelPicked);
>                  bestCollisionVel.preUncertainty = clientVelAfterInput;
>                  beforeCollisionMovement = primaryPushMovement;
> @@ -193,9 +199,14 @@
>  
>              // Close enough, there's no reason to continue our predictions (if either kb or explosion will flag, continue searching)
>              if (bestInput < 1e-5 * 1e-5 && !player.checkManager.getKnockbackHandler().wouldFlag() && !player.checkManager.getExplosionHandler().wouldFlag()) {
> -                break;
> +                // break; // force process every movement
>              }
>          }
> +
> +        // print "offset" between movements
> +        if (withoutInput != null && withInput != null) {
> +            System.out.println("input vs without input \"offset\": " + withoutInput.vector.distanceSquared(withInput.vector));
> +        }
>  
>          assert beforeCollisionMovement != null;
>  
> @@ -454,14 +465,10 @@
>              bScore -= 2;
>  
>          if (a.isWithInput() || a.isJump())
> -            aScore += 1;
> -        else
> -            aScore -= 1;
> +            aScore += 20; // over-prioritize movements without input (will cause random falses)
>  
>          if (b.isWithInput() || b.isJump())
> -            bScore += 1;
> -        else
> -            bScore -= 1;
> +            bScore += 20; // over-prioritize movements without input (will cause random falses)
>  
>          // If the player is on the ground but the vector leads the player off the ground
>          if ((player.compensatedEntities.getSelf().inVehicle() ? player.clientControlledVerticalCollision : player.onGround) && a.vector.getY() >= 0)
> ```

I applied again this patch and its still giving this issue

2023-06-23 14:21 UTC, overkidding commented
> > Are you sure you made these changes in PredictionEngine?
> 
> Yup
> 
> > > There it is https://youtu.be/RQUluYOyNMU
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/71584363/248274198-bb6b312c-de81-41cb-95a7-ba6a450c19c4.png)
> 
> Yup sure



> Are you sure you made these changes in PredictionEngine?

![image](https://github.com/GrimAnticheat/Grim/assets/46853321/0cfe092c-4043-43f0-af5c-8d72ddfe0231)

2023-09-15 20:07 UTC, MachineBreaker commented
I got some free time so i'm gonna work back on this

2023-09-16 21:56 UTC, overkidding commented
> I got some free time so i'm gonna work back on this

Fixed it my bad, found some false flags while teleporting but everything else works completely fine. Sorry for wasting your time

2023-09-16 22:46 UTC, MachineBreaker commented
> > I got some free time so i'm gonna work back on this
> 
> Fixed it my bad, found some false flags while teleporting but everything else works completely fine. Sorry for wasting your time

No problem! Are you able to contribute the false positive fix? (Or was something completely at your side?)

2023-09-17 17:24 UTC, gNewl commented
> found some false flags while teleporting

Then it's easy, to fix it you should exempt on teleport, like what it does on AimDuplicateLook

2023-09-17 18:02 UTC, overkidding commented
> > > I got some free time so i'm gonna work back on this
> > 
> > 
> > Fixed it my bad, found some false flags while teleporting but everything else works completely fine. Sorry for wasting your time
> 
> No problem! Are you able to contribute the false positive fix? (Or was something completely at your side?)

Was something completely at my side, for the teleport false flag i added this?:
![image](https://github.com/GrimAnticheat/Grim/assets/46853321/65452a70-4b2c-4824-9e97-1dc520a3a49a)

2023-09-18 21:43 UTC, MachineBreaker commented
Can someone test this now? Thanks.

2023-09-25 17:10 UTC, Souipi commented
> Can someone test this now? Thanks.

Hi I've tried the check and i bypass it with a simple NoPacketEvent.
Else i don't find any false flag for the moment with him.

2023-09-25 23:54 UTC, MachineBreaker commented
> > Can someone test this now? Thanks.
> 
> Hi I've tried the check and i bypass it with a simple NoPacketEvent. Else i don't find any false flag for the moment with him.

What packet you're cancelling?

2023-09-26 11:50 UTC, Souipi commented
> > > Can someone test this now? Thanks.
> > 
> > 
> > Hi I've tried the check and i bypass it with a simple NoPacketEvent. Else i don't find any false flag for the moment with him.
> 
> What packet you're cancelling?

I think he : ```"noopenpacket" -> {
                if (packet is C16PacketClientStatus && packet.status == C16PacketClientStatus.EnumState.OPEN_INVENTORY_ACHIEVEMENT) {
                    event.cancelEvent()
                }
            }```
            
U can find all bypasses here : https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/InvMove.kt

2023-09-26 15:46 UTC, c0dingnoobi commented
we would need a check which checks if player sends click window while our player.hasinventoryopen boolean is false
thats the only way to detect when cancelling open inv achievement

2023-09-26 18:15 UTC, MachineBreaker commented
> we would need a check which checks if player sends click window while our player.hasinventoryopen boolean is false thats the only way to detect when cancelling open inv achievement

I'm sure that would false on 1.8 (Twitch button), maybe exempting?

2023-09-26 19:05 UTC, c0dingnoobi commented
twitch button will already false every kind of gui move check 
as soon as u have the inventory open and press the twitch button 
it will close ur inventory when escaping the twitch menu  wihtout sending the close inventory packet
there is no kind of exemption for it since there is no packet received by the server

2023-09-26 19:07 UTC, c0dingnoobi commented
it should be safe to add an additional check if 1.8 player sends click window wihtout having sent open achievement (so basically player.hasinventoryopen false) 
we would have to make sure that we only do this for 1.8 clients since this is also the exact way how we detect if a 1.9 - 1.20 player has his inventory open

2023-09-26 20:17 UTC, Souipi commented
What is twitch button ?

2023-09-26 20:30 UTC, MachineBreaker commented
> What is twitch button ?

F6 in 1.8 iirc

2023-09-26 21:58 UTC, Souipi commented
> > What is twitch button ?
> 
> F6 in 1.8 iirc

Mhhhh this does not close the inventory...

2023-10-08 08:19 UTC, overkidding commented
Tested this, doesnt false with Twitch button

`
import ac.grim.grimac.GrimAPI;
import ac.grim.grimac.checks.Check;
import ac.grim.grimac.checks.CheckData;
import ac.grim.grimac.checks.type.PacketCheck;
import ac.grim.grimac.player.GrimPlayer;
import ac.grim.grimac.utils.FoliaCompatUtil;
import com.github.retrooper.packetevents.event.PacketReceiveEvent;
import com.github.retrooper.packetevents.protocol.packettype.PacketType;
import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientClickWindow;
import org.bukkit.Bukkit;

@CheckData(name = "InventoryE", setback = 3)
public class InventoryE extends Check implements PacketCheck {

    public InventoryE(GrimPlayer player) {
        super(player);
    }

    @Override
    public void onPacketReceive(PacketReceiveEvent event) {
        if (event.getPacketType() == PacketType.Play.Client.CLICK_WINDOW) {
            WrapperPlayClientClickWindow window = new WrapperPlayClientClickWindow(event);
            Bukkit.broadcastMessage(window.getWindowId() + " " + window.getButton() + " " + window.getSlot());
            // It is not possible to place a block while the inventory is open
            if (!player.hasInventoryOpen) {
                if (flagAndAlert("click window while not open")) {
                    // Cancel the packet
                    if (shouldModifyPackets()) {
                        event.setCancelled(true);
                        player.onPacketCancel();
                    }
                    FoliaCompatUtil.runTaskForEntity(player.bukkitPlayer, GrimAPI.INSTANCE.getPlugin(), () -> player.bukkitPlayer.closeInventory(), null, 0);
                }
            } else {
                reward();
            }
        }
    }
}
`

2023-10-08 15:01 UTC, MachineBreaker commented
> Tested this, doesnt false with Twitch button
> 
> `
> 
> ```
> public InventoryE(GrimPlayer player) {
>     super(player);
> }
> 
> @Override
> public void onPacketReceive(PacketReceiveEvent event) {
>     if (event.getPacketType() == PacketType.Play.Client.CLICK_WINDOW) {
>         WrapperPlayClientClickWindow window = new WrapperPlayClientClickWindow(event);
>         Bukkit.broadcastMessage(window.getWindowId() + " " + window.getButton() + " " + window.getSlot());
>         // It is not possible to place a block while the inventory is open
>         if (!player.hasInventoryOpen) {
>             if (flagAndAlert("click window while not open")) {
>                 // Cancel the packet
>                 if (shouldModifyPackets()) {
>                     event.setCancelled(true);
>                     player.onPacketCancel();
>                 }
>                 FoliaCompatUtil.runTaskForEntity(player.bukkitPlayer, GrimAPI.INSTANCE.getPlugin(), () -> player.bukkitPlayer.closeInventory(), null, 0);
>             }
>         } else {
>             reward();
>         }
>     }
> }
> ```
> 
> } `

Gonna check it soon

2023-10-11 18:33 UTC, overkidding commented
Another false flag.

**How to replicate:**
- Get a plugin that opens inventories while right clicking a sword
- Right-click the sword and sometimes you will get the false


Possible fix add the "player.packetStateData.slowedByUsingItem" check in the PredictionComplete method and return if true

`
if (!predictionComplete.isChecked() ||
                predictionComplete.getData().isTeleport() ||
                player.getSetbackTeleportUtil().blockOffsets ||
                player.packetStateData.lastPacketWasTeleport ||
                player.packetStateData.slowedByUsingItem

        ) {
            return;
        }
`

2023-10-12 09:52 UTC, MachineBreaker commented
Some commits will come in the coming days after talkiing about this with noobi

2023-10-19 21:21 UTC, overkidding commented
Found out that not only 'slowedByUsingItem' is the issue, we should check for every right-click so

System.currentTimeMillis() - player.lastBlockPlaceUseItem < 50L

should be added to the condition

`if (!predictionComplete.isChecked() ||
                predictionComplete.getData().isTeleport() ||
                player.getSetbackTeleportUtil().blockOffsets ||
                player.packetStateData.lastPacketWasTeleport ||
                player.packetStateData.slowedByUsingItem ||
                System.currentTimeMillis() - player.lastBlockPlaceUseItem < 50L

        ) {
            return;
        }`

2023-11-02 00:53 UTC, ManInMyVan commented
> Tested this, doesnt false with Twitch button

Did you press the cancel button? `E, F6, ESC, W` falses for me

A few things to be added:
  A check for rotating in inventory
  A check for if a player moves items around in their inventory while moving (for Cancel `C16PacketClientStatus.EnumState.OPEN_INVENTORY_ACHIEVEMENT`)

A few bypasses (tested on 1.8.8):
  Cancel `S2EPacketCloseWindow` (flags InventoryD once, desyncs inventory)
  Cancel `C16PacketClientStatus.EnumState.OPEN_INVENTORY_ACHIEVEMENT` (Mentioned in previous comment) 
  [FDP Client's "PacketInv" mode](https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/InvMove.kt#L123-L146) (Opens inventory > does action > Close Inventory)

2023-11-03 12:02 UTC, overkidding commented
> > Tested this, doesnt false with Twitch button
> 
> Did you press the cancel button? `E, F6, ESC, W` falses for me

Yes doesn't false (atleast in 1.8.9)

2023-11-03 12:03 UTC, overkidding commented
> [FDP Client's "PacketInv" mode](https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/InvMove.kt#L123-L146) (Opens inventory > does action > Close Inventory)


This i dont think can really be fixed unless we check for the actions in the same tick so a BadPacket check that will check if the actions are sent in the same tick

2023-11-03 12:57 UTC, overkidding commented
> A check for rotating in inventory

Working on it

2023-11-03 13:18 UTC, overkidding commented
```
package ac.grim.grimac.checks.impl.inventory;

import ac.grim.grimac.GrimAPI;
import ac.grim.grimac.checks.Check;
import ac.grim.grimac.checks.CheckData;
import ac.grim.grimac.checks.type.PostPredictionCheck;
import ac.grim.grimac.player.GrimPlayer;
import ac.grim.grimac.utils.FoliaCompatUtil;
import ac.grim.grimac.utils.anticheat.update.PredictionComplete;
import com.github.retrooper.packetevents.event.PacketReceiveEvent;
import com.github.retrooper.packetevents.protocol.packettype.PacketType;
import com.github.retrooper.packetevents.protocol.packettype.PacketTypeCommon;
import com.github.retrooper.packetevents.protocol.player.ClientVersion;
import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientClientStatus;
import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientPlayerFlying;

@CheckData(name = "InventoryF")
public class InventoryF extends Check implements PostPredictionCheck {

    public InventoryF(GrimPlayer player) {
        super(player);
    }

    private boolean hasSentOpen;

    @Override
    public void onPredictionComplete(PredictionComplete predictionComplete) {
        // call onPredictionComplete to get updated value of isTickingReliablyFor
        if (player.getClientVersion().isNewerThan(ClientVersion.V_1_8) && (!player.isTickingReliablyFor(3) || !player.skippedTickInActualMovement)) {
            hasSentOpen = false;
        }
    }

    @Override
    public void onPacketReceive(PacketReceiveEvent event) {
        PacketTypeCommon packetType = event.getPacketType();

        if (WrapperPlayClientPlayerFlying.isFlying(packetType)) {
            hasSentOpen = false;
            return;
        }

        if(event.getPacketType() == PacketType.Play.Client.CLIENT_STATUS){
            WrapperPlayClientClientStatus clientStatus = new WrapperPlayClientClientStatus(event);
            if(clientStatus.getAction() == WrapperPlayClientClientStatus.Action.OPEN_INVENTORY_ACHIEVEMENT){
                hasSentOpen = true;
            }
        }else if (event.getPacketType() == PacketType.Play.Client.CLICK_WINDOW) {
            if (hasSentOpen) {
                if (flagAndAlert("click same tick as open")) {
                    // Cancel the packet
                    if (shouldModifyPackets()) {
                        event.setCancelled(true);
                        player.onPacketCancel();
                    }
                    FoliaCompatUtil.runTaskForEntity(player.bukkitPlayer, GrimAPI.INSTANCE.getPlugin(), () -> player.bukkitPlayer.closeInventory(), null, 0);
                }
            } else {
                reward();
            }
        }
    }
}
```

2023-11-03 13:19 UTC, overkidding commented
This should patch the "PacketInv" of FDP
```
package ac.grim.grimac.checks.impl.inventory;

import ac.grim.grimac.GrimAPI;
import ac.grim.grimac.checks.Check;
import ac.grim.grimac.checks.CheckData;
import ac.grim.grimac.checks.type.PostPredictionCheck;
import ac.grim.grimac.player.GrimPlayer;
import ac.grim.grimac.utils.FoliaCompatUtil;
import ac.grim.grimac.utils.anticheat.update.PredictionComplete;
import com.github.retrooper.packetevents.event.PacketReceiveEvent;
import com.github.retrooper.packetevents.protocol.packettype.PacketType;
import com.github.retrooper.packetevents.protocol.packettype.PacketTypeCommon;
import com.github.retrooper.packetevents.protocol.player.ClientVersion;
import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientClientStatus;
import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientPlayerFlying;

@CheckData(name = "InventoryF")
public class InventoryF extends Check implements PostPredictionCheck {

    public InventoryF(GrimPlayer player) {
        super(player);
    }

    private boolean hasSentOpen;

    @Override
    public void onPredictionComplete(PredictionComplete predictionComplete) {
        // call onPredictionComplete to get updated value of isTickingReliablyFor
        if (player.getClientVersion().isNewerThan(ClientVersion.V_1_8) && (!player.isTickingReliablyFor(3) || !player.skippedTickInActualMovement)) {
            hasSentOpen = false;
        }
    }

    @Override
    public void onPacketReceive(PacketReceiveEvent event) {
        PacketTypeCommon packetType = event.getPacketType();

        if (WrapperPlayClientPlayerFlying.isFlying(packetType)) {
            hasSentOpen = false;
            return;
        }

        if(event.getPacketType() == PacketType.Play.Client.CLIENT_STATUS){
            WrapperPlayClientClientStatus clientStatus = new WrapperPlayClientClientStatus(event);
            if(clientStatus.getAction() == WrapperPlayClientClientStatus.Action.OPEN_INVENTORY_ACHIEVEMENT){
                hasSentOpen = true;
            }
        }else if (event.getPacketType() == PacketType.Play.Client.CLICK_WINDOW) {
            if (hasSentOpen) {
                if (flagAndAlert("click same tick as open")) {
                    // Cancel the packet
                    if (shouldModifyPackets()) {
                        event.setCancelled(true);
                        player.onPacketCancel();
                    }
                    FoliaCompatUtil.runTaskForEntity(player.bukkitPlayer, GrimAPI.INSTANCE.getPlugin(), () -> player.bukkitPlayer.closeInventory(), null, 0);
                }
            } else {
                reward();
            }
        }
    }
}
```

2023-11-03 13:47 UTC, overkidding commented
[inventory.patch](https://github.com/GrimAnticheat/Grim/files/13250846/inventory.patch)

This patch should be doing everything, if you could test it, would be fine @MachineBreaker

2023-11-03 14:15 UTC, MachineBreaker commented
> [inventory.patch](https://github.com/GrimAnticheat/Grim/files/13250846/inventory.patch)
> 
> This patch should be doing everything, if you could test it, would be fine @MachineBreaker

yk i don't have the entire class of that check

2023-11-03 18:24 UTC, ManInMyVan commented
> > It would be a great idea to add Extra inventory check (Crafting menu storage). I dont really know if its possible and i dont see it in any other anticheat. Also a check to see if the palyer opened his inventory in a nether portal.
> 
> If you want to give ideas, give it properly please, i don't know what means Crafting menu storage inventory check, and how we know the player didn't opened the inventory in the air then joined the portal? however, doing that gives 0 advantage

Actually, having multiple inventories open can allow for dupes on some servers. A BadPackets check or another inventory check could solve this issue.

Opening your inventory in a portal is still an advantage although small. In some cases, having this cheat can let you escape from portal traps, for example, if the server has a /spawn command, you could use this cheat to open your chat and type /spawn. Another example is, if a player is stuck in a portal trap, and has a water bucket in their inventory, they could use this cheat to open their inventory and move the water bucket to their hotbar, and place the water in portal, breaking it.

2023-11-03 19:57 UTC, overkidding commented
> > [inventory.patch](https://github.com/GrimAnticheat/Grim/files/13250846/inventory.patch)
> > This patch should be doing everything, if you could test it, would be fine @MachineBreaker
> 
> yk i don't have the entire class of that check

The patch should have everything i edited

2023-11-03 19:59 UTC, overkidding commented
> Opening your inventory in a portal is still an advantage although small. In some cases, having this cheat can let you escape from portal traps, for example, if the server has a /spawn command, you could use this cheat to open your chat and type /spawn. Another example is, if a player is stuck in a portal trap, and has a water bucket in their inventory, they could use this cheat to open their inventory and move the water bucket to their hotbar, and place the water in portal, breaking it.

This should be easy to fix, prob will work on it but i can't atm

2023-11-04 01:23 UTC, ManInMyVan commented
Also partly resolves #671

2023-11-04 04:17 UTC, MachineBreaker commented
> > > [inventory.patch](https://github.com/GrimAnticheat/Grim/files/13250846/inventory.patch)
> > > This patch should be doing everything, if you could test it, would be fine @MachineBreaker
> > 
> > 
> > yk i don't have the entire class of that check
> 
> The patch should have everything i edited

It's cut, there's a entire missing class changes

2023-11-13 01:41 UTC, ManInMyVan commented
I've come back to this, and found some more things that have not been mentioned yet:

InventoryD exempts flying players (unnecessary to do)
There is no check for sneaking while in an inventory
There is no check for changing hotbar slots while in inventory

2023-11-16 09:33 UTC, MachineBreaker commented
> I've come back to this, and found some more things that have not been mentioned yet:
> 
> InventoryD exempts flying players (unnecessary to do) There is no check for sneaking while in an inventory There is no check for changing hotbar slots while in inventory

Uh? I don't think it's worth or possible to make an inventory check for flying player as they could move and press E to open the inventory while still in movement (Remember that movement isn't stopped forcefully after opening the inventory)

2023-11-16 17:18 UTC, gNewl commented
It could also check for swing and rotations while a container is opened

2023-11-26 05:49 UTC, ManInMyVan commented
> they could move and press E to open the inventory while still in movement

What's the difference between doing this on the ground?

2023-11-26 10:50 UTC, MachineBreaker commented
> > they could move and press E to open the inventory while still in movement
> 
> What's the difference between doing this on the ground?
> 
> > rotations
> 
> Mentioned

Player movement is stopped immediately after pressing E on ground

2023-11-26 17:03 UTC, ManInMyVan commented
> Player movement is stopped immediately after pressing E on ground

I meant if you're sprint jumping or something

Edit: also ice, flowing water, knockback, pistons

2023-11-26 22:30 UTC, MachineBreaker commented
> > Player movement is stopped immediately after pressing E on ground
> 
> I meant if you're sprint jumping or something
> 
> Edit: also ice, flowing water, knockback, pistons

That's velocity

2023-11-27 05:30 UTC, ManInMyVan commented
> That's velocity

What's the difference between velocity and movement

2024-11-15 02:53 UTC, Axionize commented
Hey why is this still not merged? What issues are still left?

2024-11-15 03:15 UTC, MachineBreaker commented
> Hey why is this still not merged? What issues are still left?

It's outdated and i don't have time to update it yet, if you want to resolve the conflicts and PR it to my branch that would be cool

2024-11-16 18:13 UTC, ManInMyVan requested changes

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryA.java
> +                    alert("Attacked an entity while inventory is open");
use `flagAndAlert`

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryB.java
> +                    alert("Started digging blocks while inventory is open");
use `flagAndAlert`

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryB.java
> +                        event.setCancelled(true);
resync

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryC.java
> +                        event.setCancelled(true);
resync

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryC.java
> +                    alert("Placed a block while inventory is open");
use `flagAndAlert`

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryE.java
> +                    alert("Sent a held item change packet while inventory is open");
use `flagAndAlert`

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryE.java
> +                        event.setCancelled(true);
resync

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryF.java
> +                    alert("Sent a click window packet without a open inventory");
use `flagAndAlert`

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryF.java
> +        // once we are behind ViaVersion
did you mean ahead of?

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryG.java
> +                        event.setCancelled(true);
will cause antihunger

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryG.java
> +                    alert("Sent a entity action packet while inventory is open");
use `flagAndAlert`

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerWindow.java
> +            if(player.hasInventoryOpen && isDesynced(player)) {
```suggestion
            if (player.hasInventoryOpen && isDesynced(player)) {
```

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerWindow.java
> +}
```suggestion
}

```

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/CheckManager.java
> +import ac.grim.grimac.checks.impl.inventory.InventoryG;
```suggestion
import ac.grim.grimac.checks.impl.inventory.*;
```

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/data/VectorData.java
> +            if(x != 0 || z != 0) {
```suggestion
            if (x != 0 || z != 0) {
```

2024-11-16 18:13 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/utils/data/VectorData.java
> +            if(x != 0 || z != 0) {
```suggestion
            if (x != 0 || z != 0) {
```

2024-11-16 19:02 UTC, MachineBreaker commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryF.java
> +        // once we are behind ViaVersion
My poor english probably causing the issue here, for me behind ViaVersion means we receive the data before them but will change it

2024-11-16 19:13 UTC, MachineBreaker commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryB.java
> +                        event.setCancelled(true);
Digging packets have no resync method iirc?

2024-11-16 19:17 UTC, MachineBreaker commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryG.java
> +                        event.setCancelled(true);
Should i remove the packet modification and just close the inventory

2024-11-16 19:42 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryB.java
> +                        event.setCancelled(true);
just resync the block, like I did in BadPacketsX and BadPacketsZ

2024-11-16 22:08 UTC, ManInMyVan commented
InventoryG falses when sprinting or sneaking and opening inventory in vanilla 1.8.9
Inventory* falses with twitch button in vanilla 1.8.9

2024-11-16 22:53 UTC, MachineBreaker commented
> InventoryG falses when sprinting or sneaking and opening inventory in vanilla 1.8.9 Inventory* falses with twitch button in vanilla 1.8.9 InventoryE falses when the server sets the clients slot in vanilla 1.8.9
I dont think the twitch button is something we can fix, isnt it a client side thing?

2024-11-16 23:10 UTC, ManInMyVan commented
> I dont think the twitch button is something we can fix, isnt it a client side thing?

I don't think so

2024-11-17 01:55 UTC, ManInMyVan requested changes

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryB.java
> +            if (flagAndAlert("Started digging blocks while inventory is open")) {
check descriptions go in `@CheckData`

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryC.java
> +            if (flagAndAlert("Placed a block while inventory is open")) {
check descriptions go in `@CheckData`

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryE.java
> +                        && flagAndAlert("Sent a held item change packet while inventory is open")) {
check descriptions go in `@CheckData`

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryF.java
> +                if (flagAndAlert("Sent a click window packet without a open inventory")) {
check descriptions go in `@CheckData`

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryG.java
> +                if (flagAndAlert("Sent a entity action packet while inventory is open")) {
check descriptions go in `@CheckData`

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/impl/inventory/InventoryA.java
> +                if (flagAndAlert("Attacked an entity while inventory is open")) {
check descriptions go in `@CheckData`

2024-11-17 01:55 UTC, ManInMyVan commented on src/main/resources/punishments/es.yml
> +      - "20:20 [proxy]"
add this to all of the other punishments translations

2024-11-17 02:00 UTC, ManInMyVan requested changes

2024-11-17 02:00 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/events/packets/PacketPlayerWindow.java
> +        if (player.getClientVersion() == ClientVersion.V_1_8 &&
also happens with 1.7

2024-11-17 02:04 UTC, ManInMyVan requested changes
remove unused imports

2024-11-17 03:00 UTC, ManInMyVan requested changes

2024-11-17 03:00 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/checks/type/InventoryCheck.java
> +    // IMPORTANT: When doing checks remember to call super.onPacketReceive(event)
`@MustBeInvokedByOverriders`

2024-11-17 17:39 UTC, ManInMyVan requested changes

2024-11-17 17:39 UTC, ManInMyVan commented on src/main/java/ac/grim/grimac/manager/config/ConfigManagerFileImpl.java
> +        if (configVersion < 10) {
update the config version

2024-11-17 22:55 UTC, ManInMyVan commented
in vanilla 1.8.9:
InventoryF falses in beacons
pressing E in a nether portal falses Inventory*

2025-02-06 11:50 UTC, Axionize commented
I've added setback permissions to allow these checks to work silently and am currently working on fixing two falses, one with InventoryG which triggers if you open an inventory and jump on a horse at roughly the same time and one with InventoryD that can trigger when you are ridindg a horse which is given levitation with the inventory open (will flag InventoryD isJumping isVehicle)

2025-05-03 14:57 UTC, ghost commented
we will be merging this PR in july 2034

2025-10-06 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GrimAnticheat/Grim?pullRequest=995) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/GrimAnticheat/Grim?pullRequest=995) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: MachineBreaker<br/>:x: c0dingnoobi<br/>:x: UserNugget<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GrimAnticheat/Grim?pullRequest=995) it.</sub>

2026-02-24 08:25 UTC, Bram1903 commented
For the sake of documentation: one of the reasons `InventoryD` can false is because it doesn't take world border into account. Besides that a new Inventory check can be added that uses the input packet added in `1.21.2` to detect any form of movement while having an inventory open. Could also be merged into `InventoryD`, but given that the input packet can't be falsed by players being pushed or moved in anyway it's probably better to move that into its own check.

2026-08-17 21:00 UTC, closed without merging