pt.yml (I'm fluent - Translation)
GrimAnticheat/Grim pull request #999
Opened 2023-03-20 16:08 UTC by opZywl

2023-04-02 19:32 UTC, opZywl commented
added Portuguese translation. 
Grim is widely used on servers that speak Portuguese and that will be great

2023-04-07 22:46 UTC, gabrielvicenteYT commented
Multiple writing inconsistencies, is it “alertas”, or “sinalizações”? These have a similar meaning, but are not synonyms. Therefore, you should re-translate part of the text in order to make it both easier to understand and more readable. Keep in mind that the wall of text that I have written has multiple grammatical mistakes; though I'm trying to improve my English skills (I'm in the A1 English level).

2023-04-09 20:04 UTC, opZywl commented
I understand your questions as synonymous words, therefore, no Portuguese usually uses derivatives and these fit both in Brazilian Portuguese. than the root Portuguese itself

2023-04-11 06:43 UTC, gabrielvicenteYT commented
You created multiple unneeded, so my point still stands. You need to choose one, though both work. "Sinalizações" is better, in my opinion.

2023-04-11 06:54 UTC, gabrielvicenteYT requested changes
Though there are more things to point out, I'll admit that I'm quite lazy right now.

2023-04-11 06:54 UTC, gabrielvicenteYT commented on src/main/resources/messages/pt.yml
> +alerts-disabled: "%prefix% &fAlertas desabilitados"
Replace lines 4 and 5 with:

```
alerts-enabled: "%prefix% &fSinalizações ligadas"
alerts-disabled: "%prefix% &fSinalizações desligadas"
```

OR

```
alerts-enabled: "%prefix% &fAlertas ligados"
alerts-disabled: "%prefix% &fAlertas desligados"
```

2023-04-11 06:54 UTC, gabrielvicenteYT commented on src/main/resources/messages/pt.yml
> +  - "&bFastMath Habilitado: &f%fast_math%"
"Ligado" seems a better option than "Habilitado", since you're not going to kill "FastMath", which is "Fast Math" instead

Just for the lolz, I'll fix this too.
Replace line 35 with:
```
- "&bFast Math ligado: &f%fast_math%"
```

2023-04-11 06:54 UTC, gabrielvicenteYT commented on src/main/resources/messages/pt.yml
> +  - "/grim verbose &f- &fMostra todas as sinalizações para você, sem buffers"
Since you prefer "Alertas" (I'm starting to like it too), I'll fix this too:

Replace line 46 with:
```
- "/grim verbose &f- &fMostra todos os alertas para você, sem buffers"
- ```

2023-04-11 12:19 UTC, opZywl commented
although its words bring different meanings, it is not the correct way to use it. maybe your translation is more to portuguese from portugal

2023-04-11 16:05 UTC, gabrielvicenteYT commented
> Albeit its words bring different meanings, it is not the correct way to use it. Maybe your translation is directed to Portuguese from Portugal
Though this is true up to an extent, I continuously work on improving my translations. Either way, in 1990 in Portugal, Brazil, and a few other Portuguese-speaking countries, Portuguese almost became 1 language. The exception is formal and informal language communication types, which nearly remained the same.

2023-04-18 00:13 UTC, opZywl commented
> although its words bring different meanings, it is not the correct way to use it. maybe your translation is more to portuguese from portugal

2023-05-11 15:30 UTC, closed without merging